/**
 * Words a reader uses that the documentation does not.
 *
 * This is the one hand-written table the engine keeps, and §111 says to
 * justify every one of those. Two things it does that no extractor can:
 *
 *   it bridges Portuguese to an English corpus — "validar" shares no character
 *   with "validate" as far as BM25 is concerned, so a question written
 *   entirely in Portuguese scores zero on every literal term and the ranking
 *   is decided by these alone;
 *
 *   it bridges intent to identifier — nobody types "safeParse" when they mean
 *   "how do I check this without throwing".
 *
 * The multilingual embedding model now covers the first case properly, which
 * is why it replaced MiniLM. This table is what keeps the *lexical* half
 * working for a reader who never downloads a model at all (§78: retrieval must
 * still work at capability level 1), and it is weighted well below a literal
 * match so it can widen a search but never win one.
 */
/** Query words that name a JIT concept without using its identifier. */
export const SYNONYMS: Record<string, string[]> = {
  validation: ["validate", "parse", "safeparse"],
  validator: ["validate", "is", "parse"],
  guard: ["is", "predicate", "typeof"],
  typeguard: ["is", "predicate"],
  faster: ["benchmark", "performance", "ns"],
  fast: ["benchmark", "performance"],
  speed: ["benchmark", "performance"],
  slow: ["benchmark", "performance", "cold"],
  bundle: ["treeshaking", "aot", "generate", "imports"],
  bundlesize: ["treeshaking", "aot", "generate"],
  csp: ["aot", "browser", "function", "generate"],
  browser: ["aot", "csp", "edge"],
  copy: ["clone"],
  compare: ["equal", "diff", "hash"],
  equality: ["equal"],
  patch: ["update", "diff"],
  immutable: ["update", "draft", "reactive"],
  serialize: ["json", "stringify", "codec", "binary"],
  serialization: ["json", "stringify", "codec"],
  deserialize: ["json", "parse", "decode"],
  pii: ["mask", "security", "sanitize"],
  redact: ["mask", "security"],
  xss: ["sanitize", "security"],
  sql: ["sanitize", "sqlidentifier"],
  openapi: ["jsonschema", "dialect", "document"],
  jsonschema: ["jsonschema", "document", "draft"],
  zod: ["comparison", "standard", "schema"],
  valibot: ["comparison"],
  typebox: ["comparison"],
  typia: ["comparison", "benchmark"],
  recursive: ["lazy", "cycle", "recursion", "selfreferencing"],
  recursion: ["lazy", "cycle", "recursive"],
  cyclic: ["lazy", "cycle", "recursive"],
  migrate: ["migrating", "migration", "removed"],
  migration: ["migrating", "removed"],
  upgrade: ["migrating", "migration", "removed"],
  error: ["issue", "issues", "jitvalidationerror"],
  errors: ["issue", "issues"],
  stream: ["stream", "ndjson", "chunk", "progressive"],
  streaming: ["stream", "ndjson", "chunk"],
  big: ["binary", "rowset", "columnar"],
  large: ["binary", "rowset", "columnar", "batch"],
  memory: ["binary", "columnar", "allocation"],
  filter: ["query", "where", "eq"],
  search: ["query", "filter", "index"],
  sort: ["query", "orderby"],
  cache: ["cache", "compilecache", "hash"],
  generate: ["aot", "cli", "generate"],
  codegen: ["aot", "compile", "source"],
  compile: ["compilation", "codegen", "specialization"],
  compiles: ["compilation", "codegen", "specialization"],
  ahead: ["aot", "generate", "buildtime"],
  install: ["install", "quickstart", "npm", "pnpm"],
  start: ["quickstart", "install"],

  // The documentation is written in English and a good share of its readers
  // ask in Portuguese. Without this bridge those questions retrieve nothing at
  // all lexically, which is a worse failure than ranking something imperfectly.
  valido: ["validate", "parse", "is"],
  valida: ["validate", "parse"],
  validar: ["validate", "parse"],
  validacao: ["validate", "validation"],
  validação: ["validate", "validation"],
  alocar: ["allocation", "allocate", "zero"],
  alocacao: ["allocation", "allocate"],
  alocação: ["allocation", "allocate"],
  rapido: ["fast", "benchmark", "performance"],
  rápido: ["fast", "benchmark", "performance"],
  velocidade: ["fast", "benchmark", "performance"],
  desempenho: ["fast", "benchmark", "performance"],
  memoria: ["memory", "allocation"],
  memória: ["memory", "allocation"],
  consulta: ["query", "filter"],
  comparar: ["equal", "compare", "diff"],
  igualdade: ["equal", "compare"],
  clonar: ["clone"],
  copia: ["clone"],
  cópia: ["clone"],
  erro: ["issue", "error"],
  erros: ["issues", "error"],
  instalar: ["install", "quickstart"],
  instalo: ["install", "quickstart"],
  instalacao: ["install", "quickstart"],
  instalação: ["install", "quickstart"],
  gerar: ["generate", "aot", "cli"],
  geracao: ["generate", "aot"],
  geração: ["generate", "aot"],
  codigo: ["code", "source", "codegen"],
  código: ["code", "source", "codegen"],
  antes: ["ahead", "buildtime", "aot"],
  execucao: ["execution", "runtime", "compile"],
  execução: ["execution", "runtime", "compile"],
  navegador: ["browser", "csp", "aot"],
  fluxo: ["stream", "pipeline"],
  mascarar: ["mask", "security"],
  esconder: ["mask", "redact"],
  dados: ["data", "value"],
  sensiveis: ["sensitive", "security", "mask"],
  sensíveis: ["sensitive", "security", "mask"],
  seguranca: ["security", "sanitize", "mask"],
  segurança: ["security", "sanitize", "mask"],
  recursivo: ["recursive", "lazy", "cycle"],
  recursiva: ["recursive", "lazy", "cycle"],
  esquema: ["schema"],
  tipos: ["types", "typescript"],
  migrar: ["migrating", "migration", "removed"],
  migro: ["migrating", "migration", "removed"],
  versao: ["version", "migration"],
  versão: ["version", "migration"],
  lancar: ["throw", "safeparse", "issue"],
  lançar: ["throw", "safeparse", "issue"],
  excecao: ["exception", "safeparse", "issue"],
  exceção: ["exception", "safeparse", "issue"],
  filtro: ["filter", "query", "where"],
  filtrar: ["filter", "query", "where"],
  lista: ["list", "array", "collection"],
  listas: ["list", "array", "collection"],
  grande: ["large", "batch", "rowset", "million"],
  grandes: ["large", "batch", "rowset", "million"],
  ordenar: ["orderby", "sort"],
  agrupar: ["groupby", "group"],
  campo: ["field", "property"],
  objeto: ["object"],
  arquivo: ["file", "module"],
  tamanho: ["size", "bundle", "length"],
};
