import { stableJson } from "./artifact-json.js";
import type {
  ArtifactManifestV1,
  CompilationReceipt,
  CompilerIdentity,
  ManifestFile,
  ManifestProtocol,
  ManifestSymbol,
} from "./artifact-manifest.js";
import { sha256 } from "./hash.js";

/** One generated unit contributing symbols to a larger artifact bundle. */
export interface ArtifactBundleContribution {
  /** Stable source identity used to avoid collisions between local module ids. */
  readonly key: string;
  /** Manifest produced for this independently compiled contribution. */
  readonly manifest: ArtifactManifestV1;
  /** Compilation receipt that authenticates the contribution manifest. */
  readonly receipt: CompilationReceipt;
  /** Maps a contribution file path to its final bundle path. */
  readonly fileMap: Readonly<Record<string, string>>;
}

/** A source file already normalized for inclusion in the bundle manifest. */
export interface ArtifactBundleFile extends ManifestFile {}

/** Options for combining independently compiled project units. */
export interface ArtifactBundleOptions {
  /** Compiler identity written to the combined manifest. */
  readonly compiler?: CompilerIdentity;
  /** Optional caller-supplied digest for the combined declarations. */
  readonly declarationDigest?: string;
  /** Whether the resulting files can be regenerated by the owning compiler. */
  readonly ownership: "managed" | "detached";
  /** Source format emitted for the combined artifact. */
  readonly format: "ts" | "js";
  /** Naming policy used for generated files and symbols. */
  readonly naming: "compact" | "semantic";
}

/** The hash-bound metadata carried by a complete artifact bundle. */
export interface ArtifactBundleMetadata {
  /** Combined manifest describing every emitted file and symbol. */
  readonly manifest: ArtifactManifestV1;
  /** Receipt binding the combined manifest to its compiler inputs. */
  readonly receipt: CompilationReceipt;
}

/**
 * Combines per-module compiler results without reading generated source.
 *
 * The caller supplies the final file hashes because a browser/Lab project may
 * rename each independently compiled module before it is published. Symbol
 * ids and module ids are namespaced by the contribution key so reverse lookup
 * remains deterministic even when every unit was compiled as `index.ts`.
 */
export function createArtifactBundleMetadata(
  contributions: readonly ArtifactBundleContribution[],
  files: readonly ArtifactBundleFile[],
  options: ArtifactBundleOptions
): ArtifactBundleMetadata {
  if (contributions.length === 0) throw new Error("An artifact bundle needs at least one compilation contribution.");

  const orderedContributions = [...contributions].sort((left, right) => compareText(left.key, right.key));
  const symbolIds = createSymbolIdMap(orderedContributions);
  const symbols = orderedContributions.flatMap((contribution) =>
    contribution.manifest.symbols.map((symbol) => mapSymbol(contribution, symbol, symbolIds))
  );
  const types = orderedContributions.flatMap((contribution) =>
    contribution.manifest.types.map((type) => ({
      ...type,
      file: mapPath(contribution, type.file),
    }))
  );
  const protocols = mergeProtocols(orderedContributions, symbolIds);
  const sourceFiles = mergeFiles(files, orderedContributions, symbolIds);
  const semanticMap = mergeSemanticMap(symbols);
  const compiler = options.compiler ?? orderedContributions[0]?.manifest.compiler;
  if (!compiler) throw new Error("An artifact bundle needs a compiler identity.");

  const declarationDigest =
    options.declarationDigest ??
    sha256(stableJson(orderedContributions.map(({ key, receipt }) => ({ key, digest: receipt.declarationDigest }))));
  const programDigest = sha256(
    stableJson(orderedContributions.map(({ key, receipt }) => ({ key, digest: receipt.programDigest })))
  );
  const artifactDigest = sha256(stableJson(sourceFiles.map(({ path, hash, bytes }) => ({ path, hash, bytes }))));
  const base = {
    manifestVersion: 1 as const,
    compiler,
    declarationDigest,
    programDigest,
    artifactDigest,
    manifestDigest: "",
    ownership: options.ownership,
    emission: { format: options.format, naming: options.naming },
    files: sourceFiles,
    symbols: symbols.sort((left, right) => compareText(left.id, right.id)),
    types: types.sort((left, right) => compareText(left.file, right.file) || compareText(left.name, right.name)),
    protocols,
    semanticMap,
  } satisfies Omit<ArtifactManifestV1, "manifestDigest"> & { readonly manifestDigest: string };
  const manifest = Object.freeze({ ...base, manifestDigest: sha256(stableJson(base)) }) satisfies ArtifactManifestV1;
  const receipt = Object.freeze({
    compilerVersion: compiler.version,
    declarationDigest,
    programDigest,
    manifestDigest: manifest.manifestDigest,
    artifactDigest,
    files: sourceFiles.length,
    symbols: symbols.length,
    checks: [
      { name: "artifact-program", status: "passed" as const },
      { name: "bundle-manifest", status: "passed" as const },
      { name: "file-hashes", status: "passed" as const },
    ],
  });
  return { manifest, receipt };
}

function createSymbolIdMap(contributions: readonly ArtifactBundleContribution[]): ReadonlyMap<string, string> {
  const result = new Map<string, string>();
  for (const contribution of contributions) {
    for (const symbol of contribution.manifest.symbols) {
      result.set(symbolKey(contribution, symbol.id), `${contribution.key}:${symbol.id}`);
    }
  }
  return result;
}

function mapSymbol(
  contribution: ArtifactBundleContribution,
  symbol: ManifestSymbol,
  symbolIds: ReadonlyMap<string, string>
): ManifestSymbol {
  return {
    ...symbol,
    id: symbolIds.get(symbolKey(contribution, symbol.id)) ?? `${contribution.key}:${symbol.id}`,
    module: `${contribution.key}:${symbol.module}`,
    file: mapPath(contribution, symbol.file),
    dependencies: symbol.dependencies.map(
      (dependency) => symbolIds.get(symbolKey(contribution, dependency)) ?? `${contribution.key}:${dependency}`
    ),
  };
}

function mergeProtocols(
  contributions: readonly ArtifactBundleContribution[],
  symbolIds: ReadonlyMap<string, string>
): readonly ManifestProtocol[] {
  const groups = new Map<
    string,
    { protocol: string; version: number; input: string; output: string; symbols: Set<string> }
  >();
  for (const contribution of contributions) {
    for (const protocol of contribution.manifest.protocols) {
      const key = `${protocol.protocol}:${protocol.version}:${protocol.input}:${protocol.output}`;
      const group = groups.get(key) ?? {
        protocol: protocol.protocol,
        version: protocol.version,
        input: protocol.input,
        output: protocol.output,
        symbols: new Set<string>(),
      };
      for (const symbol of protocol.symbols) {
        group.symbols.add(symbolIds.get(symbolKey(contribution, symbol)) ?? `${contribution.key}:${symbol}`);
      }
      groups.set(key, group);
    }
  }
  return [...groups.values()]
    .map((group) => ({ ...group, symbols: [...group.symbols].sort(compareText) }))
    .sort((left, right) => compareText(`${left.protocol}:${left.version}`, `${right.protocol}:${right.version}`));
}

function mergeFiles(
  files: readonly ArtifactBundleFile[],
  contributions: readonly ArtifactBundleContribution[],
  symbolIds: ReadonlyMap<string, string>
): readonly ManifestFile[] {
  const sourceByPath = new Map<
    string,
    { readonly contribution: ArtifactBundleContribution; readonly file: ManifestFile }
  >();
  for (const contribution of contributions) {
    for (const file of contribution.manifest.files) {
      const path = mapPath(contribution, file.path);
      sourceByPath.set(path, { contribution, file });
    }
  }
  return [...files]
    .map((file) => {
      const source = sourceByPath.get(file.path);
      if (!source) return { ...file, exports: [], imports: [] };
      return {
        ...file,
        exports: source.file.exports.map(
          (symbol) => symbolIds.get(symbolKey(source.contribution, symbol)) ?? `${source.contribution.key}:${symbol}`
        ),
        imports: source.file.imports.map((dependency) => ({
          module: `${source.contribution.key}:${dependency.module}`,
          symbols: dependency.symbols.map(
            (symbol) => symbolIds.get(symbolKey(source.contribution, symbol)) ?? `${source.contribution.key}:${symbol}`
          ),
        })),
      };
    })
    .sort((left, right) => compareText(left.path, right.path));
}

function mergeSemanticMap(symbols: readonly ManifestSymbol[]): ArtifactManifestV1["semanticMap"] {
  const groups = new Map<string, Set<string>>();
  for (const symbol of symbols) {
    const values = groups.get(symbol.declaration) ?? new Set<string>();
    values.add(symbol.id);
    groups.set(symbol.declaration, values);
  }
  return {
    declarations: [...groups.entries()]
      .map(([declaration, ids]) => ({ declaration, symbols: [...ids].sort(compareText) }))
      .sort((left, right) => compareText(left.declaration, right.declaration)),
  };
}

function mapPath(contribution: ArtifactBundleContribution, path: string): string {
  return contribution.fileMap[path] ?? path;
}

function symbolKey(contribution: ArtifactBundleContribution, id: string): string {
  return `${contribution.key}\u0000${id}`;
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}
