import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";
import { MOCK_HELPERS } from "../compiler/mock.js";
import { JSON_PATCH_HELPERS, PATCH_EQUAL_HELPER } from "../compiler/patch.js";
import { resolvePerformanceProfile } from "../compiler/performance/profile.js";
import { resolvePhysicalPlan, resolveValidationPhysicalPlan } from "../compiler/physical/physical-plan.js";
import { resolveWrappers } from "../compiler/resolvers/resolve-wrappers.js";
import { resolveLazySchema, schemaChildren } from "../compiler/schema-recursion.js";
import { STRATEGY_CATALOG_VERSION } from "../compiler/strategy/catalog.js";
import { portableProfile } from "../compiler/target/portable-profile.js";
import { resolveDeploymentTargetProfile } from "../compiler/target/resolve-target.js";
import type { TargetDescriptor, TargetProfile } from "../compiler/target/target-profile.js";
import type * as ATS from "../core/ats/index.js";
import { TypeName } from "../core/ats/index.js";
import type { SchemaInput } from "../core/builder/index.js";
import { unwrapSchema } from "../core/builder/index.js";
import { type CompiledArtifact, getArtifact } from "../runtime/artifact-registry.js";
import { isValidIdentifier } from "../shared/parse.js";
import {
  type ArtifactManifestV1,
  type ArtifactOwnership,
  type CompilationReceipt,
  createArtifactManifest,
  createCompilationReceipt,
  hashArtifactFile,
  inspectArtifactStatus,
  type ManifestPhysicalPlan,
  sha256,
  stableJson,
} from "./artifact-manifest.js";
import {
  type ArtifactProgram,
  type ProtocolCapability,
  relativeModuleImport,
  topologicalModuleOrder,
} from "./artifact-program.js";
import { declarationImportType, memberImportType } from "./artifact-types.js";
import {
  type ArtifactProgramModuleInput,
  buildArtifactProgram,
  declarationRevisionDigest,
} from "./build-artifact-program.js";
import type { ArtifactTypeContext } from "./emit-artifact-type.js";
import { type ArtifactEmitterFlag, createArtifactEmitter, type EmittedBinding } from "./emit-artifacts.js";
import type { ClassArtifactEmitContext } from "./emit-class-types.js";
import { emitTypeScriptType } from "./emit-type.js";
import { type NamingProfile, SemanticNameAllocator } from "./semantic-name.js";
import { serializeCallback } from "./serialize-callback.js";

/** One declaration the generator could not build, and why. */
export interface SkippedOperation {
  readonly schema: string;
  readonly operation: string;
  readonly reason: string;
}

/** `"ts"` emits one typed module; `"js"` emits ready-to-run ESM. */
export type AotOutputFormat = "ts" | "js";

/** First line of every generated module; also the ownership marker for `clean`. */
const GENERATED_BANNER = "// Generated by jit — do not edit.";
const JIT_COMPILER_VERSION = "2.0.0";
const CALL_HELPER =
  "type __JitCall<TFunction> = TFunction extends (...args: infer A) => infer R ? (...args: A) => R : never;";

/** Describes the JIT generate options contract used by the public API. */
export interface GenerateOptions {
  /** Explicit target profile used for physical-plan reproducibility metadata. */
  readonly target?: TargetDescriptor;
  /** Declaration name -> compiled artifact, emitted as one exported function. */
  readonly artifacts?: Readonly<Record<string, unknown>>;
  /** Declaration name -> object of artifacts, emitted as one frozen object. */
  readonly groups?: Readonly<Record<string, Readonly<Record<string, unknown>>>>;
  /** Explicit generated type name -> schema. */
  readonly schemas?: Readonly<Record<string, SchemaInput>>;
  /** Output directory. Previous JIT output there is always replaced. */
  readonly outDir: string;
  /**
   * Source format. `ts` keeps public signatures in the executable source
   * itself and leaves type resolution to the application's own build; `js`
   * emits ready-to-run ESM. The low-level API defaults to `js` while
   * CLI/config default to `ts`.
   */
  readonly format?: AotOutputFormat;
  /**
   * Emit one module per declaration file, named after it, plus an `index`
   * barrel. Requires `sources`; defaults to a single `index` module.
   */
  readonly perFile?: boolean;
  /**
   * Declaration name -> file it was declared in. Drives per-file module
   * names and the precise types of artifacts whose signature can only be
   * read back from the declaration itself.
   */
  readonly sources?: ReadonlyMap<string, string>;
  /** Declaration names the source file exports; those get precise types. */
  readonly exported?: ReadonlySet<string>;
  /** Explicit logical module path for each declaration, without an extension. */
  readonly modulePaths?: Readonly<Record<string, string>>;
  /** Keep the compiler as source of truth for the generated tree. */
  readonly ownership?: ArtifactOwnership;
  /** Identifier profile used by compiler-generated helper names. */
  readonly naming?: NamingProfile;
  /** Emit a hash-bound `jit.manifest.json` and `jit.receipt.json` sidecar. */
  readonly emitManifest?: boolean;
  /** Relative manifest path below `outDir`; defaults to `jit.manifest.json`. */
  readonly manifestPath?: string;
  /** Relative receipt path below `outDir`; defaults to `jit.receipt.json`. */
  readonly receiptPath?: string;
  /** Explicit protocol capabilities keyed by generated export name. */
  readonly protocols?: Readonly<Record<string, readonly ProtocolCapability[]>>;
  /** Optional caller-owned declaration digest used by project tooling. */
  readonly declarationDigest?: string;
  /** Use structural portable error names in generated code; defaults to true. */
  readonly portableErrors?: boolean;
  /** Explicitly allow replacing a modified managed artifact tree. */
  readonly overwriteModified?: boolean;
}

/** Describes the JIT generate result contract used by the public API. */
export interface GenerateResult {
  readonly files: readonly string[];
  readonly skipped: readonly SkippedOperation[];
  /** Lowered program shared by runtime and source materialization. */
  readonly program?: ArtifactProgram;
  /** Hash-bound semantic index emitted when manifest sidecars are requested. */
  readonly manifest?: ArtifactManifestV1;
  /** Verifiable compiler and artifact digest record paired with the manifest. */
  readonly receipt?: CompilationReceipt;
}

interface ModulePlan {
  readonly name: string;
  readonly artifacts: Readonly<Record<string, unknown>>;
  readonly groups: Readonly<Record<string, Readonly<Record<string, unknown>>>>;
  readonly schemas: Readonly<Record<string, SchemaInput>>;
}

interface EmittedModule {
  readonly name: string;
  readonly plan: ModulePlan;
  readonly source: string;
  readonly exports: readonly string[];
  readonly types: readonly string[];
  readonly skipped: readonly SkippedOperation[];
}

interface OutputLayout {
  readonly format: AotOutputFormat;
  readonly extension: ".js" | ".ts";
}

interface ClassLocation {
  readonly value: unknown;
  readonly module: string;
  readonly name: string;
  readonly artifact: Extract<CompiledArtifact, { readonly kind: "class" }>;
}

interface ClassArtifactIndex {
  readonly byValue: ReadonlyMap<unknown, ClassLocation>;
  readonly bySchema: ReadonlyMap<ATS.AnyTypeSchema, ClassLocation>;
}

/** A group member or standalone export, already lowered to a binding. */

/**
 * Prisma-style AOT generation: turns declarations into one optimized `.js`
 * or directly typed `.ts` module written to a directory the app imports. The
 * generated module is fully self-contained — the few tiny runtime helpers a
 * strategy may need (validation error class, keyed-index cache) are inlined
 * into the file, so it has zero imports: no engine weight, no module graph
 * to load on cold start, CSP-safe.
 *
 * A declaration file exposes an explicit manifest. `export type User =
 * JIT.Typeof<typeof userSchema>` names a generated type; `export const isUser
 * = JIT.validate.is(userSchema)` becomes `isUser`; and an exported object of
 * artifacts becomes one frozen object with exactly those members.
 */
export function generate(options: GenerateOptions): GenerateResult {
  const layout = resolveOutputLayout(assertOutputFormat(options.format ?? "js"));
  // AOT has no ambient engine contract. Without an explicit deployment target
  // use the portable profile so the build machine cannot silently determine
  // generated source.
  const target = options.target === undefined ? portableProfile : resolveDeploymentTargetProfile(options.target);
  const naming = options.naming ?? "compact";
  const skipped: SkippedOperation[] = [];
  const modules: EmittedModule[] = [];
  const plans = planModules(options);
  const classIndex = indexClassArtifacts(plans);

  if (options.emitManifest === true && options.ownership !== "detached" && options.overwriteModified !== true) {
    const existing = inspectArtifactStatus(
      options.outDir,
      options.manifestPath ?? "jit.manifest.json",
      options.receiptPath ?? "jit.receipt.json"
    );
    if (existing.status === "modified") {
      throw new Error(
        `Managed artifact tree has modified generated files: ${(existing.files ?? []).join(", ")}. Set overwriteModified=true to replace it.`
      );
    }
  }

  for (const plan of plans) {
    const emitted = emitModule(plan, options, layout, classIndex, target);

    skipped.push(...emitted.skipped);
    if (emitted.exports.length > 0 || emitted.types.length > 0) modules.push(emitted);
  }

  if (modules.length === 0) return { files: [], skipped };

  const programModules: ArtifactProgramModuleInput[] = modules.map((module) => ({
    name: module.name,
    path: `${module.name}${layout.extension}`,
    exports: module.exports,
    types: module.types,
    artifacts: module.plan.artifacts,
    groups: module.plan.groups,
    schemas: module.plan.schemas,
  }));
  // Semantic lowering completes before any filesystem write. The emitter
  // receives the graph only for materialization decisions such as barrel order;
  // it never discovers dependencies by scanning generated source.
  const program = buildArtifactProgram({
    modules: programModules,
    includeBarrel: options.perFile === true,
    ...(options.perFile === true ? { barrelPath: `index${layout.extension}` } : {}),
    ...(options.protocols ? { protocols: options.protocols } : {}),
  });

  const preservedGeneratedNames = new Set([
    ...modules.map((module) => `${module.name}${layout.extension}`),
    ...(options.perFile === true ? [`index${layout.extension}`] : []),
  ]);
  cleanGeneratedFiles(options.outDir, preservedGeneratedNames);
  mkdirSync(options.outDir, { recursive: true });

  const files = modules.map((module) => writeFile(options.outDir, `${module.name}${layout.extension}`, module.source));

  if (options.perFile === true) {
    files.push(writeFile(options.outDir, `index${layout.extension}`, emitBarrel(modules, layout, program)));
  }

  if (options.emitManifest !== true) return { files, skipped, program };

  const manifest = createArtifactManifest({
    compiler: { name: "jit", version: JIT_COMPILER_VERSION },
    declarationDigest:
      options.declarationDigest ??
      declarationRevisionDigest({
        modules: programModules,
        includeBarrel: options.perFile === true,
        ...(options.perFile === true ? { barrelPath: `index${layout.extension}` } : {}),
        ...(options.protocols ? { protocols: options.protocols } : {}),
      }),
    program,
    fileHashes: program.modules.map((module) => hashArtifactFile(options.outDir, module)),
    ownership: options.ownership ?? "managed",
    format: layout.format,
    naming,
    target,
    performanceProfileVersion: performanceVersion(target),
    strategyCatalogVersion: STRATEGY_CATALOG_VERSION,
    physicalPlanDigest: physicalPlanDigest(options, target),
    physicalPlans: physicalPlans(options, target),
  });
  const receipt = createCompilationReceipt(manifest, JIT_COMPILER_VERSION, [
    { name: "artifact-program", status: "passed" },
    { name: "manifest-symbols", status: "passed" },
    { name: "file-hashes", status: "passed" },
  ]);
  const manifestFile = writeMetadata(options.outDir, options.manifestPath ?? "jit.manifest.json", manifest);
  const receiptFile = writeMetadata(options.outDir, options.receiptPath ?? "jit.receipt.json", receipt);

  return { files: [...files, manifestFile, receiptFile], skipped, program, manifest, receipt };
}

function physicalPlanDigest(
  options: GenerateOptions,
  target: ReturnType<typeof resolveDeploymentTargetProfile>
): string {
  const plans = physicalPlans(options, target).map(({ symbol, digest }) => ({ name: symbol, digest }));
  return sha256(stableJson({ target: target.digest, plans }));
}

function performanceVersion(target: ReturnType<typeof resolveDeploymentTargetProfile>): string {
  const profile = resolvePerformanceProfile(target);
  return `${profile.id}@${profile.version}`;
}

function physicalPlans(
  options: GenerateOptions,
  target: ReturnType<typeof resolveDeploymentTargetProfile>
): readonly ManifestPhysicalPlan[] {
  const plans: ManifestPhysicalPlan[] = [];
  for (const [name, value] of Object.entries(options.artifacts ?? {})) {
    const plan = physicalPlanForArtifact(name, value, target);
    if (plan !== undefined) plans.push(plan);
  }
  for (const [groupName, group] of Object.entries(options.groups ?? {})) {
    for (const [name, value] of Object.entries(group)) {
      const plan = physicalPlanForArtifact(`${groupName}.${name}`, value, target);
      if (plan !== undefined) plans.push(plan);
    }
  }
  return Object.freeze(plans.sort((left, right) => left.symbol.localeCompare(right.symbol)));
}

function physicalPlanForArtifact(
  symbol: string,
  value: unknown,
  target: ReturnType<typeof resolveDeploymentTargetProfile>
): ManifestPhysicalPlan | undefined {
  const artifact = getArtifact(value);
  const physical =
    artifact?.kind === "execution"
      ? resolvePhysicalPlan(artifact.plan, target)
      : artifact?.kind === "validator"
        ? resolveValidationPhysicalPlan(artifact.schema, artifact.op, target)
        : undefined;
  if (physical === undefined) return undefined;
  return {
    symbol,
    target: physical.target.id,
    digest: physical.digest,
    strategyCatalogVersion: physical.strategyCatalogVersion,
    performanceProfileVersion: physical.performanceProfileVersion,
    extensions: physical.optimization.semanticExtensions,
    capabilities: physical.capabilities.map((capability) => ({
      kind: capability.kind,
      ...(capability.key === undefined ? {} : { key: capability.key }),
      sourceStage: capability.sourceStage,
      reusable: capability.reusable,
    })),
    decisions: physical.decisions.map((decision) => ({
      family: decision.family,
      strategy: decision.strategy,
      reason: decision.reason,
      evidence: decision.evidence,
      estimated: {
        runtime: decision.estimated.runtime,
        allocation: decision.estimated.allocation,
        setup: decision.estimated.setup,
        codeSize: decision.estimated.codeSize,
        ...(decision.estimated.cold === undefined ? {} : { cold: decision.estimated.cold }),
        ...(decision.estimated.branches === undefined ? {} : { branches: decision.estimated.branches }),
      },
    })),
  };
}

/** One module per declaration file, or a single `index` holding everything. */
function planModules(options: GenerateOptions): readonly ModulePlan[] {
  const artifacts = options.artifacts ?? {};
  const groups = options.groups ?? {};
  const schemas = options.schemas ?? {};
  const sources = options.sources;

  if (options.perFile !== true || (!sources && !options.modulePaths))
    return [{ name: "index", artifacts, groups, schemas }];

  const names = [...Object.keys(artifacts), ...Object.keys(groups), ...Object.keys(schemas)];
  const byFile = new Map<string, string[]>();

  for (const name of names) {
    const explicitModulePath = options.modulePaths?.[name];
    const file = explicitModulePath ?? sources?.get(name);

    if (!file) continue;
    const bucket = byFile.get(file);

    if (bucket) bucket.push(name);
    else byFile.set(file, [name]);
  }

  const used = new Set<string>();

  return [...byFile].map(([file, declared]) => {
    const selected = new Set(declared);
    const explicitModulePath = declared.map((name) => options.modulePaths?.[name]).find((path) => path !== undefined);

    return {
      name: uniqueModuleName(
        explicitModulePath === undefined ? moduleNameFromSource(file) : normalizeModulePath(explicitModulePath),
        used
      ),
      artifacts: pick(artifacts, selected),
      groups: pick(groups, selected),
      schemas: pick(schemas, selected),
    };
  });
}

function indexClassArtifacts(plans: readonly ModulePlan[]): ClassArtifactIndex {
  const byValue = new Map<unknown, ClassLocation>();
  const bySchema = new Map<ATS.AnyTypeSchema, ClassLocation>();

  for (const plan of plans) {
    for (const [name, value] of Object.entries(plan.artifacts)) {
      const artifact = getArtifact(value);
      if (!isValidIdentifier(name) || artifact?.kind !== "class") continue;
      const location: ClassLocation = { value, module: plan.name, name, artifact };
      byValue.set(value, location);
      bySchema.set(artifact.schema, location);
      if (artifact.declaredSchema !== undefined) bySchema.set(artifact.declaredSchema, location);
    }
  }

  return { byValue, bySchema };
}

function referencedClasses(plan: ModulePlan, index: ClassArtifactIndex): readonly ClassLocation[] {
  const result = new Map<unknown, ClassLocation>();
  const seen = new WeakSet<ATS.AnyTypeSchema>();
  const visit = (schema: ATS.AnyTypeSchema): void => {
    const current = resolveLazySchema(schema);
    const location = index.bySchema.get(current) ?? index.bySchema.get(resolveWrappers(current).base);
    if (location !== undefined) result.set(location.value, location);
    if (seen.has(current)) return;
    seen.add(current);
    for (const child of schemaChildren(current)) visit(child);
  };

  const visitValue = (value: unknown): void => {
    const artifact = getArtifact(value);
    if (artifact !== undefined && "schema" in artifact) {
      visit(artifact.schema as ATS.AnyTypeSchema);
      return;
    }
    try {
      visit(unwrapSchema(value as SchemaInput<ATS.AnyTypeSchema>));
    } catch {
      // Non-schema groups and constants have no nested Runtime Type references.
    }
  };

  for (const value of Object.values(plan.artifacts)) visitValue(value);
  for (const group of Object.values(plan.groups)) {
    for (const value of Object.values(group)) visitValue(value);
  }
  for (const schema of Object.values(plan.schemas)) visitValue(schema);

  return [...result.values()].sort(
    (left, right) => compareText(left.module, right.module) || compareText(left.name, right.name)
  );
}

function pick<TValue>(record: Readonly<Record<string, TValue>>, selected: ReadonlySet<string>): Record<string, TValue> {
  return Object.fromEntries(Object.entries(record).filter(([name]) => selected.has(name)));
}

function emitBarrel(modules: readonly EmittedModule[], layout: OutputLayout, program: ArtifactProgram): string {
  const lines = [GENERATED_BANNER];
  const byName = new Map(modules.map((module) => [module.name, module] as const));
  const ordered = topologicalModuleOrder(program)
    .filter((module) => module.id !== "index")
    .map((module) => byName.get(module.id))
    .filter((module): module is EmittedModule => module !== undefined);

  for (const module of ordered) {
    if (layout.format === "ts" && module.types.length > 0) {
      lines.push(`export type { ${module.types.join(", ")} } from "./${module.name}.js";`);
    }
    if (module.exports.length > 0) {
      lines.push(`export { ${module.exports.join(", ")} } from "./${module.name}.js";`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function emitModule(
  plan: ModulePlan,
  options: GenerateOptions,
  layout: OutputLayout,
  classIndex: ClassArtifactIndex,
  target: TargetProfile
): EmittedModule {
  const ts = layout.format === "ts";
  const skipped: SkippedOperation[] = [];
  const js: string[] = [];
  const tsTypes: string[] = [];
  const exportNames: string[] = [];
  const typeNames = new Map<ATS.AnyTypeSchema, string>();
  // A construct stage may refer to a Runtime Class emitted by this module.
  // Keep the source-level binding instead of serializing the runtime
  // constructor as an external closure value.
  const classBindings = new Map<unknown, string>();
  const classArtifacts = new Map<unknown, Extract<CompiledArtifact, { readonly kind: "class" }>>();
  const classImports: string[] = [];
  const importedClasses = new Set<string>();
  const assertionBindings = new Map<unknown, string>();
  const assertionSources: string[] = [];
  const publicNames = new Set([...Object.keys(plan.artifacts), ...Object.keys(plan.groups)]);
  const internalNames = new Set<string>();
  const nameAllocator = new SemanticNameAllocator(options.naming ?? "compact");
  const exported = options.exported ?? new Set<string>();
  let needsRuntimeGetIndex = false;
  let needsRuntimeCachedIndex = false;
  let needsValidationError = false;
  let needsAssertionError = false;
  let needsHashHelpers = false;
  let needsHashCache = false;
  let needsJsonPatchHelpers = false;
  let needsMockHelpers = false;
  let needsCallHelper = false;
  let needsAggregateType = false;
  let needsDomainStateType = false;
  let needsDomainEventType = false;

  for (const name of publicNames) nameAllocator.reserve("module", name);

  for (const reference of referencedClasses(plan, classIndex)) {
    if (reference.module === plan.name) continue;
    const alias = nameAllocator.allocate({
      role: "binding",
      preferred: reference.name,
      path: [reference.module, reference.name],
      scope: "module",
    });
    const importKey = `${reference.module}\u0000${reference.name}\u0000${alias}`;
    if (importedClasses.has(importKey)) continue;
    importedClasses.add(importKey);
    const modulePath = relativeModuleImport(`${plan.name}.js`, `${reference.module}.js`);
    classImports.push(
      alias === reference.name
        ? `import { ${reference.name} } from ${JSON.stringify(modulePath)};`
        : `import { ${reference.name} as ${alias} } from ${JSON.stringify(modulePath)};`
    );
    classBindings.set(reference.value, alias);
    classArtifacts.set(reference.value, reference.artifact);
  }

  for (const [name, value] of Object.entries(plan.artifacts)) {
    const artifact = getArtifact(value);

    if (isValidIdentifier(name) && artifact?.kind === "class") {
      classBindings.set(value, name);
      classArtifacts.set(value, artifact);
    }
  }

  // Runtime Type schemas carry a compiled assertion guard so the runtime
  // validator can fuse child invariants into the parent's issue buffer. AOT
  // can reconstruct that guard from the declaration-time assertion IR; keep
  // the generated function at module scope so nested validators bind it like
  // any other emitted class artifact.
  for (const [value, artifact] of classArtifacts) {
    const assertion = artifact.policy?.assertions;
    const schema = (value as { readonly schema?: ATS.AnyTypeSchema }).schema;
    if (assertion === undefined || schema?.type !== TypeName.runtimeType) continue;
    const runtimeSchema = schema as ATS.RuntimeTypeSchema;
    if (runtimeSchema.def.assertion === undefined) continue;
    const helper = internalIdentifier(`${classBindings.get(value) ?? "runtime"}_assertion`);
    const lines = [`const ${helper} = /*#__PURE__*/ (() => {`];
    const bindingLines = inlineBindings(assertion.bindingNames, assertion.bindingValues);
    if (bindingLines === undefined) {
      skipped.push({
        schema: classBindings.get(value) ?? "runtime class",
        operation: "class.assert",
        reason: "an assertion value cannot be serialized ahead of time",
      });
      continue;
    }
    lines.push(...bindingLines.map((line) => `  ${line}`));
    for (const [index, failure] of assertion.failures.entries()) {
      lines.push(
        `  const __issue${index} = Object.freeze(${JSON.stringify({
          path: failure.field === undefined ? [] : [failure.field],
          code: failure.code,
          expected: failure.rule ?? "a domain invariant",
          message: failure.message,
        })});`,
        `  const __fail${index} = () => undefined;`
      );
    }
    lines.push(...indentBlock(assertion.source).map((line) => `  ${line}`), "  return __assert;", "})();");
    assertionSources.push(...lines);
    assertionBindings.set(runtimeSchema.def.assertion, helper);
  }

  // Every explicitly requested type is named first, so a schema nested inside another
  // is emitted as its own name instead of being inlined a second time.
  // A generated type and a generated value may share a name: TypeScript keeps
  // them in separate declaration spaces, so `User.is(value)` and `User` as a
  // type both read naturally from the same declaration file.
  for (const name of Object.keys(plan.schemas)) {
    if (!isValidIdentifier(name)) continue;
    const schema = unwrapSchema(plan.schemas[name] as SchemaInput<ATS.AnyTypeSchema>);

    if (!typeNames.has(schema)) typeNames.set(schema, name);
  }

  const typeExports = Object.entries(plan.schemas).flatMap(([name, input]) => {
    if (!isValidIdentifier(name)) return [];
    const schema = unwrapSchema(input as SchemaInput<ATS.AnyTypeSchema>);

    tsTypes.push(`export type ${name} = ${emitTypeScriptType(schema, typeNames)};`);
    return [name];
  });

  js.push(GENERATED_BANNER);
  if (classImports.length > 0) js.push(...classImports, "");
  const typePrelude = ts
    ? [
        "type __JitValue = any;",
        "type __JitValidationIssue = { readonly path: readonly PropertyKey[]; readonly code: string; readonly expected: string; readonly message: string; readonly received?: string; readonly params?: Readonly<Record<string, unknown>>; };",
        "type __JitSafeParse<T> = { readonly success: true; readonly data: T } | { readonly success: false; readonly issues: readonly __JitValidationIssue[] };",
        "",
      ]
    : [];
  js.push(...typePrelude);
  js.push(...assertionSources);
  if (assertionSources.length > 0) js.push("");

  const mark = (flag: ArtifactEmitterFlag): void => {
    switch (flag) {
      case "runtimeGetIndex":
        needsRuntimeGetIndex = true;
        break;
      case "runtimeCachedIndex":
        needsRuntimeCachedIndex = true;
        break;
      case "hashHelpers":
        needsHashHelpers = true;
        break;
      case "hashCache":
        needsHashCache = true;
        break;
      case "jsonPatchHelpers":
        needsJsonPatchHelpers = true;
        break;
      case "validationError":
        needsValidationError = true;
        break;
      case "assertionError":
        needsAssertionError = true;
        break;
      case "aggregateType":
        needsAggregateType = true;
        break;
      case "domainStateType":
        needsDomainStateType = true;
        break;
      case "domainEventType":
        needsDomainEventType = true;
        break;
      case "mockHelpers":
        needsMockHelpers = true;
        break;
      case "callHelper":
        needsCallHelper = true;
        break;
    }
  };

  const classArtifactContext: Omit<ClassArtifactEmitContext, "emitValidatorBinding" | "emitHashBinding"> = {
    js,
    typescript: ts,
    skipped,
    mark,
    internalIdentifier,
    classMemberName,
    inlineBindings,
    serializeBindingValue,
    indentBlock,
    asExpression,
    tryEmit,
    classBindings,
    assertionBindings,
    hasNestedValidation,
  };

  const artifactTypeContext: ArtifactTypeContext = {
    typeNames,
    classMemberName,
    classUpdateType,
    mark,
  };

  const emitArtifact = createArtifactEmitter({
    js,
    skipped,
    ts,
    target,
    artifactTypeContext,
    classArtifactContext,
    classBindings,
    classArtifacts,
    assertionBindings,
    mark,
    internalIdentifier,
    inlineBindings,
    inlineCodecBindings,
    serializeBindingValue,
    serializeStaticData,
    asExpression,
    indentBlock,
    tryEmit,
  });

  for (const [name, members] of Object.entries(plan.groups)) {
    if (!isValidIdentifier(name)) {
      skipped.push({
        schema: name,
        operation: "group",
        reason: "declaration names must be valid JavaScript identifiers",
      });
      continue;
    }

    const sourceFile = options.sources?.get(name);
    const operations: (EmittedBinding & { readonly prop: string })[] = [];

    for (const prop of Object.keys(members)) {
      const artifact = getArtifact(members[prop]);

      if (!artifact) {
        skipped.push({
          schema: name,
          operation: prop,
          reason: "member is not a compiled JIT artifact",
        });
        continue;
      }

      const memberType =
        exported.has(name) && sourceFile
          ? memberImportType(options.outDir, sourceFile, name, prop, artifact)
          : undefined;
      const emitted = emitArtifact(
        internalIdentifier(`${name}_${prop}`),
        artifact,
        `${name}.${prop}`,
        memberType,
        false
      );

      if (emitted) {
        emitProtocolAdapters(
          js,
          emitted.binding,
          artifact,
          options.protocols?.[`${name}.${prop}`],
          `${name}.${prop}`,
          skipped
        );
        operations.push({ prop, ...emitted });
      }
    }

    if (operations.length === 0) {
      skipped.push({
        schema: name,
        operation: "group",
        reason: "no member of this object could be generated",
      });
      continue;
    }

    if (ts) {
      js.push(`const ${name}: {`);
      js.push(...operations.map((operation) => `  readonly ${operation.prop}: ${operation.type};`));
      js.push("} = /*#__PURE__*/ Object.freeze({");
    } else {
      js.push(`const ${name} = /*#__PURE__*/ Object.freeze({`);
    }
    js.push(...operations.map((operation) => `  ${operation.prop}: ${operation.binding},`));
    js.push("});");
    js.push("");
    exportNames.push(name);
  }

  for (const [name, value] of Object.entries(plan.artifacts)) {
    if (!isValidIdentifier(name)) {
      skipped.push({
        schema: name,
        operation: "export",
        reason: "declaration names must be valid JavaScript identifiers",
      });
      continue;
    }

    const artifact = getArtifact(value);

    if (!artifact) {
      skipped.push({
        schema: name,
        operation: "export",
        reason: "declaration is not a compiled JIT artifact",
      });
      continue;
    }

    const sourceFile = options.sources?.get(name);
    const declaredType =
      exported.has(name) && sourceFile ? declarationImportType(options.outDir, sourceFile, name, artifact) : undefined;

    const emitted = emitArtifact(name, artifact, name, declaredType, ts);
    if (emitted) {
      emitProtocolAdapters(js, emitted.binding, artifact, options.protocols?.[name], name, skipped);
      exportNames.push(name);
    }
  }

  function internalIdentifier(preferred: string): string {
    if (options.naming === "semantic") {
      return nameAllocator.allocate({ role: "temporary", preferred, scope: "module" });
    }
    let candidate = preferred;
    let suffix = 1;

    while (publicNames.has(candidate) || internalNames.has(candidate)) candidate = `${preferred}_${suffix++}`;

    internalNames.add(candidate);
    return candidate;
  }

  function classMemberName(name: string): string {
    return isValidIdentifier(name) ? name : `[${JSON.stringify(name)}]`;
  }

  function classUpdateType(schema: ATS.AnyTypeSchema, seen = new Set<ATS.AnyTypeSchema>()): string {
    if (seen.has(schema)) return emitTypeScriptType(schema, typeNames);
    const resolved = resolveWrappers(schema);
    const base = resolved.base;

    if (base.type === TypeName.object) {
      seen.add(schema);
      const fields = Object.entries((base as ATS.ObjectSchema).def.props)
        .filter(([, child]) => !resolveWrappers(child).readonly)
        .map(([key, child]) => `${JSON.stringify(key)}?: ${classUpdateType(child, seen)}`);
      seen.delete(schema);
      return fields.length === 0 ? "{}" : `{ ${fields.join("; ")} }`;
    }
    if (base.type === TypeName.array) {
      const element = (base as ATS.ArraySchema).def.element;
      return `(${classUpdateType(element, seen)} | undefined)[]`;
    }
    return emitTypeScriptType(schema, typeNames);
  }

  // Inlined runtime helpers keep the module import-free: nothing from the
  // engine is loaded in production, and cold start pays only this file.
  const helpers: string[] = [];

  if (needsAssertionError) {
    helpers.push(
      "class DomainAssertionError extends Error {",
      ...(ts
        ? [
            '  readonly code: "ASSERTION_FAILED";',
            "  readonly rule: string | undefined;",
            "  readonly field: string | undefined;",
            "  readonly issues: readonly __JitValidationIssue[];",
            "  readonly path: readonly PropertyKey[] | undefined;",
          ]
        : []),
      `  constructor(message${ts ? ": string" : ""}, details${ts ? ": { readonly rule?: string; readonly field?: string; readonly issues?: readonly __JitValidationIssue[] } | undefined" : ""}) {`,
      "    super(message);",
      '    this.name = "DomainAssertionError";',
      '    this.code = "ASSERTION_FAILED";',
      "    this.rule = details?.rule;",
      "    this.field = details?.field;",
      "    this.issues = details?.issues ?? [];",
      "    this.path = details?.field === undefined ? undefined : [details.field];",
      "  }",
      "}"
    );
  }
  if (needsValidationError) {
    helpers.push(
      "class JITValidationError extends Error {",
      ...(ts ? ['  readonly code: "VALIDATION_FAILED";', "  readonly issues: readonly __JitValidationIssue[];"] : []),
      `  constructor(issues${ts ? ": readonly __JitValidationIssue[]" : ""}) {`,
      "    const first = issues[0];",
      `    const path = first ? first.path.map((segment${ts ? ": PropertyKey" : ""}, index${ts ? ": number" : ""}) => typeof segment === "number" ? "[" + segment + "]" : (index === 0 ? "" : ".") + String(segment)).join("") : "";`,
      '    super(first ? (path === "" ? "" : path + ": ") + first.message : "validation failed");',
      '    this.name = "JITValidationError";',
      '    this.code = "VALIDATION_FAILED";',
      "    this.issues = issues;",
      "  }",
      "}"
    );
  }
  if (needsHashHelpers) {
    const hashValue = ts ? "value: __JitValue" : "value";
    const hashNumber = ts ? "value: __JitValue" : "value";
    const hashResult = ts ? ": number" : "";
    const hashPair = ts ? "left: __JitValue, right: __JitValue" : "left, right";
    helpers.push(
      `function __hashNumber(${hashNumber})${hashResult} { return value | 0; }`,
      `function __hashBoolean(${hashValue})${hashResult} { return value ? 1 : 0; }`,
      `function __hashBigInt(${hashValue})${hashResult} { return Number(value & 0xffffffffn) | 0; }`,
      `function __hashString(${hashValue})${hashResult} {`,
      "  let hash = 0;",
      "  for (let i = 0, len = value.length; i < len; i++) {",
      "    hash = (hash * 31 + value.charCodeAt(i)) | 0;",
      "  }",
      "  return hash;",
      "}",
      `function __hashUnknown(${hashValue})${ts ? ": __JitValue" : ""} {`,
      "  switch (typeof value) {",
      '    case "string": return __hashString(value);',
      '    case "number": return __hashNumber(value);',
      '    case "boolean": return __hashBoolean(value);',
      '    case "bigint": return __hashBigInt(value);',
      '    case "undefined": return 0;',
      '    case "symbol": return __hashString(String(value));',
      '    case "object": return value === null ? 1 : __hashString(Object.prototype.toString.call(value));',
      '    case "function": return __hashString("function");',
      "  }",
      "}",
      `function __combineHash(${hashPair})${hashResult} { return ((left << 5) - left + right) | 0; }`
    );
    if (needsHashCache)
      helpers.unshift(
        ts ? "const __hashCache: WeakMap<object, number> = new WeakMap();" : "const __hashCache = new WeakMap();"
      );
  }
  if (needsJsonPatchHelpers) helpers.push(...JSON_PATCH_HELPERS.split("\n"), ...PATCH_EQUAL_HELPER.split("\n"));
  if (needsMockHelpers) helpers.push(...MOCK_HELPERS.split("\n"));
  if (needsRuntimeGetIndex) {
    helpers.push(
      "const __indexCache = new WeakMap();",
      "function __getIndex(items, key) {",
      "  const cached = __indexCache.get(items);",
      "  if (cached !== undefined && cached.key === key) return cached.map;",
      "  const map = new Map();",
      "  for (let i = 0, len = items.length; i < len; i++) map.set(items[i][key], items[i]);",
      "  __indexCache.set(items, { key: key, map: map });",
      "  return map;",
      "}"
    );
  }
  if (needsRuntimeCachedIndex) {
    helpers.push(
      "const __planCache = new WeakMap();",
      "function __cachedIndex(items, cacheKey, build) {",
      "  let plans = __planCache.get(items);",
      "  if (plans === undefined) { plans = new Map(); __planCache.set(items, plans); }",
      "  const cached = plans.get(cacheKey);",
      "  if (cached !== undefined) return cached;",
      "  const built = build(items);",
      "  plans.set(cacheKey, built);",
      "  return built;",
      "}"
    );
  }

  const importPreludeLength = classImports.length > 0 ? classImports.length + 1 : 0;
  const preludeIndex =
    1 + importPreludeLength + typePrelude.length + assertionSources.length + (assertionSources.length > 0 ? 1 : 0);

  if (helpers.length > 0) js.splice(preludeIndex, 0, ...helpers);
  if (ts && tsTypes.length > 0) js.splice(preludeIndex, 0, ...tsTypes, "");
  if (ts && needsDomainStateType) {
    js.splice(preludeIndex, 0, "declare class __JitDomainState<TProps> {", "  protected readonly _props: TProps;", "}");
  }
  if (ts && needsDomainEventType) {
    js.splice(
      preludeIndex,
      0,
      "declare const __JitDomainEvent: unique symbol;",
      "interface __JitDomainEventBrand { readonly [__JitDomainEvent]: true; }"
    );
  }
  if (ts && needsAggregateType) {
    js.splice(
      preludeIndex,
      0,
      "declare class __JitAggregate<TPatch, TEvent extends __JitDomainEventBrand> {",
      "  protected raise(event: TEvent): void;",
      "  peekEvents(): readonly TEvent[];",
      "  pullEvents(): TEvent[];",
      "  commit(publisher: { publish(event: TEvent): void | PromiseLike<void> }): Promise<void>;",
      "}"
    );
  }
  if (ts && needsCallHelper) js.splice(preludeIndex, 0, CALL_HELPER);

  const source =
    exportNames.length > 0
      ? `${js.join("\n")}\nexport { ${exportNames.join(", ")} };\n`
      : `${js.join("\n")}\nexport {};\n`;
  const portableSource =
    options.portableErrors !== false ? source.split("JITValidationError").join("ValidationError") : source;

  return {
    name: plan.name,
    plan,
    source: portableSource,
    exports: exportNames,
    types: ts ? typeExports : [],
    skipped,
  };
}

function emitProtocolAdapters(
  js: string[],
  binding: string,
  artifact: CompiledArtifact,
  capabilities: readonly ProtocolCapability[] | undefined,
  reportName: string,
  skipped: SkippedOperation[]
): void {
  for (const capability of capabilities ?? []) {
    const protocol = capability.protocol;
    if (protocol === "standard-schema" || protocol === "standard-schema/v1") {
      if (!isStandardSchemaBoundary(artifact) || capability.version !== 1 || capability.input !== "unknown") {
        skipped.push({
          schema: reportName,
          operation: protocol,
          reason: "protocol input/output does not match a parser boundary",
        });
        continue;
      }
      js.push(
        `Object.defineProperty(${binding}, "~standard", { enumerable: false, configurable: false, value: Object.freeze({ version: 1, vendor: "jit", validate(value) { try { return { value: ${binding}(value) }; } catch (error) { const issues = error && typeof error === "object" ? error.issues : undefined; if (!issues) throw error; return { issues: issues.map((issue) => ({ message: issue.message, ...(issue.path && issue.path.length > 0 ? { path: issue.path } : {}) })) }; } } }) });`
      );
      continue;
    }
    if (protocol === "standard-json-schema" || protocol === "standard-json-schema/v1") {
      if (
        artifact.kind !== "operation" ||
        artifact.op !== "jsonSchema" ||
        capability.version !== 1 ||
        capability.input !== "schema" ||
        capability.output !== "json-schema"
      ) {
        skipped.push({
          schema: reportName,
          operation: protocol,
          reason: "protocol input/output does not match a JSON Schema document boundary",
        });
        continue;
      }
      // A JSON Schema artifact is already the protocol document. The
      // capability is recorded in the manifest; no callable adapter or JIT
      // helper is needed at runtime.
      continue;
    }
    skipped.push({
      schema: reportName,
      operation: protocol,
      reason: "protocol capability is not supported by this AOT emitter",
    });
  }
}

function isStandardSchemaBoundary(artifact: CompiledArtifact): boolean {
  if (artifact.kind === "validator") return artifact.op === "parse";
  if (artifact.kind !== "execution") return false;
  const stage = artifact.plan.stages[artifact.plan.stages.length - 1];
  return stage?.kind === "validate" && stage.operation === "parse";
}

/**
 * Artifacts built from a developer callback chain (queries, mappers,
 * watchers) have no runtime metadata precise enough to rebuild their
 * signature, so the generated module reads it back from the declaration
 * that produced it. That reference is type-only and disappears at build.
 */
function moduleNameFromSource(sourceFile: string): string {
  const rawName = basename(sourceFile)
    .replace(/\.jit\.(ts|mts|cts|js|mjs|cjs)$/, "")
    .replace(/\.(ts|mts|cts|js|mjs|cjs)$/, "");
  const normalized = rawName.replace(/[^A-Za-z0-9_-]/g, "-").replace(/^-+|-+$/g, "");

  return normalized.length > 0 ? normalized : "schema";
}

function uniqueModuleName(preferred: string, used: Set<string>): string {
  let candidate = preferred;
  let suffix = 1;

  while (used.has(candidate) || candidate === "index") candidate = `${preferred}-${++suffix}`;
  used.add(candidate);
  return candidate;
}

function tryEmit<TValue>(
  schema: string,
  operation: string,
  skipped: SkippedOperation[],
  emit: () => TValue
): TValue | undefined {
  try {
    return emit();
  } catch (error) {
    skipped.push({
      schema,
      operation,
      reason: error instanceof Error ? error.message : String(error),
    });
    return undefined;
  }
}

/**
 * Serializes compiler bindings into const declarations. Developer callbacks
 * are emitted as source so generated modules stay self-contained and do not
 * pay a runtime compiler cost.
 */
function inlineBindings(names: readonly string[], values: readonly unknown[]): string[] | undefined {
  const lines: string[] = [];

  for (let index = 0; index < names.length; index++) {
    const value = values[index];
    const literal = serializeBindingValue(value);

    if (literal === undefined) return undefined;

    lines.push(`const ${names[index]} = ${literal};`);
  }

  return lines;
}

function inlineCodecBindings(names: readonly string[], values: readonly unknown[]): string[] | undefined {
  const lines: string[] = [];

  for (let index = 0; index < names.length; index++) {
    const name = names[index];
    const value = values[index];

    if (name === "__enc") {
      lines.push("const __enc = new TextEncoder();");
      continue;
    }

    if (name === "__dec") {
      lines.push("const __dec = new TextDecoder();");
      continue;
    }

    const literal = serializeBindingValue(value);

    if (literal === undefined) return undefined;

    lines.push(`const ${name} = ${literal};`);
  }

  return lines;
}

function serializeBindingValue(value: unknown): string | undefined {
  if (value instanceof RegExp) return String(value);
  if (typeof value === "function") return serializeCallback(value);
  if (value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return JSON.stringify(value);
  }
  if (value === undefined) return "undefined";
  if (Array.isArray(value)) {
    const parts = value.map(serializeBindingValue);

    if (parts.some((part) => part === undefined)) return undefined;
    return `[${parts.join(", ")}]`;
  }

  return undefined;
}

/** Whether an unvalidated materializer still has an explicitly validated child. */
function hasNestedValidation(schema: ATS.AnyTypeSchema, seen = new Set<ATS.AnyTypeSchema>()): boolean {
  const current = resolveLazySchema(schema);
  if (seen.has(current)) return false;
  seen.add(current);

  if (current.type === TypeName.runtimeType) {
    const runtime = current as ATS.RuntimeTypeSchema;
    if (runtime.def.traits.factoryPolicy.validationConfigured === true || runtime.def.assertion !== undefined)
      return true;
  }

  return schemaChildren(current).some((child) => hasNestedValidation(child, seen));
}

/** Serializes data-only update patches without evaluating getters or prototypes. */
function serializeStaticData(value: unknown, seen = new Set<object>()): string | undefined {
  if (value === null) return "null";

  switch (typeof value) {
    case "string":
      return JSON.stringify(value);
    case "boolean":
      return value ? "true" : "false";
    case "undefined":
      return "undefined";
    case "bigint":
      return `${value}n`;
    case "number":
      if (Number.isNaN(value)) return "NaN";
      if (value === Infinity) return "Infinity";
      if (value === -Infinity) return "-Infinity";
      if (Object.is(value, -0)) return "-0";
      return String(value);
    case "object":
      return serializeStaticObject(value, seen);
    default:
      return undefined;
  }
}

function serializeStaticObject(value: object, seen: Set<object>): string | undefined {
  if (seen.has(value)) return undefined;
  seen.add(value);

  try {
    if (value instanceof Date) {
      const time = value.getTime();
      return Number.isNaN(time) ? "new Date(NaN)" : `new Date(${time})`;
    }

    if (Array.isArray(value)) return serializeStaticArray(value, seen);

    return serializeStaticRecord(value, seen);
  } finally {
    seen.delete(value);
  }
}

function serializeStaticArray(value: readonly unknown[], seen: Set<object>): string | undefined {
  const items = value.map((item) => serializeStaticData(item, seen));

  if (items.some((item) => item === undefined)) return undefined;
  return `[${items.join(", ")}]`;
}

function serializeStaticRecord(value: object, seen: Set<object>): string | undefined {
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) return undefined;
  const descriptors = Object.getOwnPropertyDescriptors(value);
  const entries: string[] = [];

  for (const key of Object.keys(descriptors)) {
    const descriptor = descriptors[key];
    if (descriptor === undefined || !("value" in descriptor)) return undefined;
    const entry = serializeStaticData(descriptor.value, seen);
    if (entry === undefined) return undefined;
    entries.push(`${JSON.stringify(key)}: ${entry}`);
  }
  return `{ ${entries.join(", ")} }`;
}

/**
 * Wraps an emitted source so it reads as a single expression.
 *
 * A schema with a cycle emits one named helper per participant alongside its
 * entry point, so the source is a sequence of declarations rather than one
 * function expression. Those are evaluated once and the entry point returned
 * by name — order-independent, and the same shape the runtime `Function` body
 * already has. An acyclic source is a lone function expression and is
 * parenthesized exactly as before.
 */
function asExpression(source: string, entry: string): string {
  const trimmed = source.trimStart();

  // Already a self-contained expression — a serializer wraps its own IIFE.
  if (!trimmed.startsWith("function ")) return `(${source})`;

  // Bodies are indented, so a top-level match counts declarations. One means
  // the historical single-function shape, which is parenthesized unchanged.
  const declarations = trimmed.match(/^function /gm)?.length ?? 0;

  if (declarations <= 1) return `(${source})`;

  return `/*#__PURE__*/ (() => {\n${source}\nreturn ${entry};\n})()`;
}

function resolveOutputLayout(format: AotOutputFormat): OutputLayout {
  return { format, extension: format === "ts" ? ".ts" : ".js" };
}

function assertOutputFormat(value: unknown): AotOutputFormat {
  if (value === "ts" || value === "js") return value;
  throw new Error(`unknown AOT output format ${JSON.stringify(value)}; expected "ts" or "js"`);
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function indentBlock(source: string): string[] {
  return source.split("\n").map((line) => (line.length > 0 ? `  ${line}` : line));
}

function writeFile(dir: string, name: string, content: string): string {
  const path = join(/* turbopackIgnore: true */ dir, name);

  mkdirSync(dirname(path), { recursive: true });
  try {
    if (readFileSync(path, "utf8") !== content) writeFileSync(path, content);
  } catch {
    writeFileSync(path, content);
  }
  return path;
}

function writeMetadata(dir: string, name: string, value: unknown): string {
  if (isAbsolute(name)) throw new Error(`Artifact metadata path must be relative to outDir: ${name}`);
  const path = join(/* turbopackIgnore: true */ dir, name);
  const escaped = relative(resolve(dir), resolve(path));
  if (escaped === ".." || escaped.startsWith("../") || escaped.startsWith("..\\")) {
    throw new Error(`Artifact metadata path escapes outDir: ${name}`);
  }
  mkdirSync(dirname(path), { recursive: true });
  const content = `${JSON.stringify(value, null, 2)}\n`;
  try {
    if (readFileSync(path, "utf8") !== content) writeFileSync(path, content);
  } catch {
    writeFileSync(path, content);
  }
  return path;
}

/**
 * Removes JIT-owned output from a previous generation — including modules
 * from a different layout or from declaration files that no longer exist —
 * without ever touching a file JIT did not write. Ownership is decided by
 * the generated banner, not by a name list.
 */
function cleanGeneratedFiles(dir: string, preservedNames: ReadonlySet<string> = new Set()): void {
  cleanGeneratedDirectory(dir, "", preservedNames);
}

function cleanGeneratedDirectory(dir: string, relativeDir: string, preservedNames: ReadonlySet<string>): void {
  let entries: readonly import("node:fs").Dirent[];

  try {
    entries = readdirSync(/* turbopackIgnore: true */ dir, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    const path = join(/* turbopackIgnore: true */ dir, entry.name);
    const relativeName = relativeDir.length === 0 ? entry.name : `${relativeDir}/${entry.name}`;
    if (preservedNames.has(relativeName)) continue;

    if (entry.isDirectory()) {
      if (entry.name === "plans") {
        rmSync(path, { recursive: true, force: true });
        continue;
      }
      cleanGeneratedDirectory(path, relativeName, preservedNames);
      continue;
    }
    if (
      entry.name === "manifest.json" ||
      entry.name === "package.json" ||
      entry.name === "jit.manifest.json" ||
      entry.name === "jit.receipt.json"
    ) {
      if (isGeneratedJson(path)) rmSync(path, { force: true });
      continue;
    }
    if (/\.(?:m|c)?[jt]s$/.test(entry.name) && isGeneratedSource(path)) rmSync(path, { force: true });
  }
}

function isGeneratedSource(path: string): boolean {
  try {
    return readFileSync(path, "utf8").startsWith(GENERATED_BANNER);
  } catch {
    return false;
  }
}

function isGeneratedJson(path: string): boolean {
  // Metadata from earlier JIT layouts; a hand-written manifest is left alone.
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8")) as {
      readonly version?: unknown;
      readonly sideEffects?: unknown;
      readonly manifestVersion?: unknown;
      readonly artifactDigest?: unknown;
      readonly manifestDigest?: unknown;
    };

    return (
      parsed.version === 2 ||
      parsed.version === "0.0.0" ||
      parsed.sideEffects === false ||
      parsed.manifestVersion === 1 ||
      (typeof parsed.artifactDigest === "string" && typeof parsed.manifestDigest === "string")
    );
  } catch {
    return false;
  }
}

function normalizeModulePath(value: string): string {
  const withoutExtension = value.replace(/\.(?:m|c)?[jt]s$/, "").replace(/\\/g, "/");
  const segments = withoutExtension.split("/");
  if (
    withoutExtension.length === 0 ||
    segments.some((segment) => segment.length === 0 || segment === "." || segment === "..")
  ) {
    throw new Error(`Invalid artifact module path ${JSON.stringify(value)}.`);
  }
  return segments
    .map((segment) => segment.replace(/[^A-Za-z0-9_$-]/g, "-").replace(/^-+|-+$/g, "") || "module")
    .join("/");
}
