import { mkdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { emitCloneSource } from "../compiler/clone.js";
import { emitCodec } from "../compiler/codec/emit-codec.js";
import { emitEqualSource } from "../compiler/equal.js";
import { emitHashSource } from "../compiler/hash.js";
import { emitMaskSource } from "../compiler/mask.js";
import { emitSanitizeSource, sanitizeChainBindings } from "../compiler/sanitize.js";
import { emitSerialize } from "../compiler/serialize/emit-serialize.js";
import { emitValidator } from "../compiler/validate/emit-validate.js";
import type * as ATS from "../core/ats/index.js";
import type { SchemaInput } from "../core/builder/index.js";
import { unwrapSchema } from "../core/builder/index.js";
import { getArtifact } from "../runtime/artifact-registry.js";
import { emitTypeScriptType } from "./emit-type.js";

/** One schema operation skipped by the generator and why. */
export interface SkippedOperation {
  readonly schema: string;
  readonly operation: string;
  readonly reason: string;
}

export interface GenerateOptions {
  /** Exported name → schema (or builder) to generate for. */
  readonly schemas: Readonly<Record<string, SchemaInput>>;
  /** Output directory; created if missing (e.g. `node_modules/@jit/generated`). */
  readonly outDir: string;
  /** Generated package name; defaults to `@jit/generated`. */
  readonly packageName?: string;
  /**
   * Schema name → source file it was loaded from. When present, the
   * generated `.d.ts` derives the value type from the dev's own schema via
   * `import("jit").Infer<typeof import("<file>").Name>` — the single source
   * of truth for typing — instead of re-emitting a structural type by hand.
   * Type-only imports erase at runtime, so tree-shaking is unaffected.
   */
  readonly sources?: ReadonlyMap<string, string>;
}

export interface GenerateResult {
  readonly files: readonly string[];
  readonly skipped: readonly SkippedOperation[];
}

/**
 * Prisma-style AOT generation: turns schemas into plain, optimized `.js`
 * plus `.d.ts`, written to a directory the app imports directly. The
 * generated module is fully self-contained — the few tiny runtime helpers
 * a strategy may need (validation error class, keyed-index cache) are
 * inlined into the file, so it has zero imports: no engine weight, no
 * module graph to load on cold start, CSP-safe.
 *
 * Each schema becomes a namespace constant (`export const User = { is,
 * parse, safeParse, equal, clone, stringify, mask, sanitize, codec }`);
 * operations whose bindings cannot be serialized (user callbacks in
 * refine/transform/default) are skipped and reported.
 */
export function generate(options: GenerateOptions): GenerateResult {
  const packageName = options.packageName ?? "@jit/generated";
  const skipped: SkippedOperation[] = [];
  const js: string[] = [];
  const dts: string[] = [];
  const exportNames: string[] = [];
  let needsRuntimeGetIndex = false;
  let needsValidationError = false;
  let needsHashHelpers = false;

  js.push("// Generated by jit — do not edit.");
  dts.push("// Generated by jit — do not edit.");

  for (const name of Object.keys(options.schemas)) {
    const schema = unwrapSchema(options.schemas[name] as SchemaInput<ATS.AnyTypeSchema>);
    const operations: { readonly prop: string; readonly type: string }[] = [];
    const sourceFile = options.sources?.get(name);
    // JIT.compile(schema, ops) markers restrict generation to the chosen ops.
    const requested = readRequestedOps(options.schemas[name]);
    const wants = (op: string): boolean => requested === undefined || requested.includes(op);

    if (requested) {
      for (const op of requested) {
        if (!AOT_OPS.has(op)) {
          skipped.push({
            schema: name,
            operation: op,
            reason: "runtime-only operation (not generated ahead of time)",
          });
        }
      }
    }

    if (sourceFile) {
      const specifier = typeImportSpecifier(options.outDir, sourceFile);

      dts.push(`export type ${name} = import("jit").Infer<typeof import(${JSON.stringify(specifier)}).${name}>;`);
    } else {
      // No source file to anchor to (programmatic generate): fall back to a
      // structural type emitted from the schema tree.
      dts.push(`export type ${name} = ${emitTypeScriptType(schema)};`);
    }

    // is / parse / safeParse
    const wantsValidator = wants("is") || wants("parse") || wants("safeParse");
    const validator = wantsValidator ? tryEmit(name, "validator", skipped, () => emitValidator(schema)) : undefined;

    if (validator) {
      const inlined = inlineBindings(validator.bindings.names, validator.bindings.values);

      if (inlined === undefined) {
        skipped.push({
          schema: name,
          operation: "validator",
          reason: "refine/transform/default callbacks cannot be serialized ahead of time",
        });
      } else {
        js.push(`const ${name}_validator = /*#__PURE__*/ (() => {`);
        js.push(...inlined.map((line) => `  ${line}`));
        js.push(...indentBlock(validator.source));
        js.push("})();");
        if (wants("is")) {
          // Pure-call accessors (not property reads) so bundlers can drop
          // each function — and the validator itself — when unused.
          js.push(`const ${name}_is = /*#__PURE__*/ ((v) => v.is)(${name}_validator);`);
          operations.push({
            prop: "is",
            type: `(value: unknown) => value is ${name}`,
          });
        }
        if (wants("safeParse")) {
          js.push(`const ${name}_safeParse = /*#__PURE__*/ ((v) => v.safeParse)(${name}_validator);`);
          operations.push({
            prop: "safeParse",
            type: `(value: unknown) => { readonly success: true; readonly data: ${name} } | { readonly success: false; readonly issues: readonly { readonly path: string; readonly code: string; readonly expected: string; readonly message: string; readonly received?: string }[] }`,
          });
        }
        if (wants("parse")) {
          needsValidationError = true;
          js.push(
            `const ${name}_parse = /*#__PURE__*/ ((v) => (value) => { const r = v.safeParse(value); if (r.success) return r.data; throw new JITValidationError(r.issues); })(${name}_validator);`
          );
          operations.push({
            prop: "parse",
            type: `(value: unknown) => ${name}`,
          });
        }
      }
    }

    // equal source first: it decides whether hash helpers are required.
    const equalSource = wants("equal") ? tryEmit(name, "equal", skipped, () => emitEqualSource(schema)) : undefined;
    const equalNeedsHash = equalSource?.includes("__hash");

    // hash (also powers hash-short-circuit equal)
    const hashSource =
      wants("hash") || equalNeedsHash ? tryEmit(name, "hash", skipped, () => emitHashSource(schema)) : undefined;

    if (hashSource) {
      needsHashHelpers = true;
      js.push(`const ${name}_hash = /*#__PURE__*/ (() => {`);
      js.push(...indentBlock(`const compute = (${hashSource});`));
      js.push("  return (value) => {");
      js.push('    if ((typeof value === "object" && value !== null) || typeof value === "function") {');
      js.push("      const cached = __hashCache.get(value);");
      js.push("      if (cached !== undefined) return cached;");
      js.push("      const hash = compute(value);");
      js.push("      __hashCache.set(value, hash);");
      js.push("      return hash;");
      js.push("    }");
      js.push("    return compute(value);");
      js.push("  };");
      js.push("})();");
      if (wants("hash")) operations.push({ prop: "hash", type: `(value: ${name}) => number` });
    }

    // equal
    if (equalSource) {
      const needsHash = equalSource.includes("__hash");
      const needsIndex = equalSource.includes("__getIndex");

      if (needsHash && !hashSource) {
        skipped.push({
          schema: name,
          operation: "equal",
          reason: "hash short-circuit hints need an emittable hash",
        });
      } else {
        if (needsIndex) needsRuntimeGetIndex = true;
        if (needsHash) {
          js.push(`const ${name}_equal = /*#__PURE__*/ ((__hash) => (${equalSource}))(${name}_hash);`);
        } else {
          js.push(`const ${name}_equal = (${equalSource});`);
        }
        operations.push({
          prop: "equal",
          type: `(left: ${name}, right: ${name}) => boolean`,
        });
      }
    }

    // clone
    const cloneSource = wants("clone") ? tryEmit(name, "clone", skipped, () => emitCloneSource(schema)) : undefined;

    if (cloneSource) {
      js.push(`const ${name}_clone = (${cloneSource});`);
      operations.push({ prop: "clone", type: `(value: ${name}) => ${name}` });
    }

    // stringify
    const serializeSource = wants("stringify")
      ? tryEmit(name, "stringify", skipped, () => emitSerialize(schema))
      : undefined;

    if (serializeSource) {
      js.push(`const ${name}_stringify = (${serializeSource});`);
      operations.push({
        prop: "stringify",
        type: `(value: ${name}) => string`,
      });
    }

    // mask
    const maskSource = wants("mask") ? tryEmit(name, "mask", skipped, () => emitMaskSource(schema)) : undefined;

    if (maskSource) {
      js.push(`const ${name}_mask = (${maskSource});`);
      operations.push({ prop: "mask", type: `(value: ${name}) => ${name}` });
    }

    // sanitize
    const sanitizeSource = wants("sanitize")
      ? tryEmit(name, "sanitize", skipped, () => emitSanitizeSource(schema))
      : undefined;

    if (sanitizeSource) {
      const regexConsts = sanitizeChainBindings.names.map(
        (bindingName, position) => `const ${bindingName} = ${String(sanitizeChainBindings.values[position])};`
      );

      js.push(`const ${name}_sanitize = /*#__PURE__*/ (() => {`);
      js.push(...regexConsts.map((line) => `  ${line}`));
      js.push(...indentBlock(`return (${sanitizeSource});`));
      js.push("})();");
      operations.push({
        prop: "sanitize",
        type: `(value: ${name}) => ${name}`,
      });
    }

    // codec
    const codec = wants("codec") ? tryEmit(name, "codec", skipped, () => emitCodec(schema)) : undefined;

    if (codec) {
      const inlined = inlineCodecBindings(codec.bindingNames, codec.bindingValues);

      if (inlined === undefined) {
        skipped.push({
          schema: name,
          operation: "codec",
          reason: "codec bindings cannot be serialized",
        });
      } else {
        js.push(`const ${name}_codec = /*#__PURE__*/ (() => {`);
        js.push(...inlined.map((line) => `  ${line}`));
        js.push(...indentBlock(codec.source));
        js.push("})();");
        operations.push({
          prop: "codec",
          type: `{ readonly encode: (value: ${name}) => Uint8Array; readonly encodeInto: (value: ${name}, target: Uint8Array) => number; readonly decode: (bytes: Uint8Array | ArrayBuffer) => ${name} }`,
        });
      }
    }

    // Dev-defined extras (compiled queries/mappers aggregated via
    // JIT.compile): re-emitted from their registered source + bindings.
    for (const extraName of readExtraNames(options.schemas[name])) {
      const artifact = getArtifact((options.schemas[name] as Record<string, unknown>)[extraName]);

      if (!artifact) {
        skipped.push({
          schema: name,
          operation: extraName,
          reason: "extra is not a registered compiled artifact (query/mapper)",
        });
        continue;
      }

      const inlined = inlineBindings(artifact.bindingNames, artifact.bindingValues);

      if (inlined === undefined) {
        skipped.push({
          schema: name,
          operation: extraName,
          reason: `${artifact.kind} bindings hold callbacks that cannot be serialized ahead of time`,
        });
        continue;
      }

      js.push(`const ${name}_${extraName} = /*#__PURE__*/ (() => {`);
      js.push(...inlined.map((line) => `  ${line}`));
      js.push(`  return (${artifact.source});`);
      js.push("})();");

      const extraType = sourceFile
        ? `typeof import(${JSON.stringify(typeImportSpecifier(options.outDir, sourceFile))}).${name}[${JSON.stringify(extraName)}]`
        : "unknown";

      operations.push({ prop: extraName, type: extraType });
    }

    // Flat exports make each operation independently tree-shakable; the
    // namespace is a pure aggregation bundlers can drop when unused.
    js.push(`const ${name} = /*#__PURE__*/ Object.freeze({`);
    js.push(...operations.map((operation) => `  ${operation.prop}: ${name}_${operation.prop},`));
    js.push("});");
    js.push("");

    for (const operation of operations) {
      exportNames.push(`${name}_${operation.prop}`);
      dts.push(`export declare const ${name}_${operation.prop}: ${operation.type};`);
    }
    exportNames.push(name);

    dts.push(`export declare const ${name}: {`);
    dts.push(...operations.map((operation) => `  readonly ${operation.prop}: typeof ${name}_${operation.prop};`));
    dts.push("};");
    dts.push("");
  }

  // Inlined runtime helpers keep the module import-free: nothing from the
  // engine is loaded in production, and cold start pays only this file.
  const helpers: string[] = [];

  if (needsValidationError) {
    helpers.push(
      "class JITValidationError extends Error {",
      "  constructor(issues) {",
      "    const first = issues[0];",
      '    super(first ? (first.path ? first.path + ": " : "") + first.message : "validation failed");',
      '    this.name = "JITValidationError";',
      '    this.code = "VALIDATION_FAILED";',
      "    this.issues = issues;",
      "  }",
      "}"
    );
  }
  if (needsHashHelpers) {
    helpers.push(
      "const __hashCache = new WeakMap();",
      "function __hashNumber(value) { return value | 0; }",
      "function __hashBoolean(value) { return value ? 1 : 0; }",
      "function __hashBigInt(value) { return Number(value & 0xffffffffn) | 0; }",
      "function __hashString(value) {",
      "  let hash = 0;",
      "  for (let i = 0, len = value.length; i < len; i++) {",
      "    hash = (hash * 31 + value.charCodeAt(i)) | 0;",
      "  }",
      "  return hash;",
      "}",
      "function __hashUnknown(value) {",
      "  switch (typeof value) {",
      '    case "string": return __hashString(value);',
      '    case "number": return __hashNumber(value);',
      '    case "boolean": return __hashBoolean(value);',
      '    case "bigint": return __hashBigInt(value);',
      '    case "undefined": return 0;',
      '    case "symbol": return __hashString(String(value));',
      '    case "object": return value === null ? 1 : __hashString(Object.prototype.toString.call(value));',
      '    case "function": return __hashString("function");',
      "  }",
      "}",
      "function __combineHash(left, right) { return ((left << 5) - left + right) | 0; }"
    );
  }
  if (needsRuntimeGetIndex) {
    helpers.push(
      "const __indexCache = new WeakMap();",
      "function __getIndex(items, key) {",
      "  const cached = __indexCache.get(items);",
      "  if (cached !== undefined && cached.key === key) return cached.map;",
      "  const map = new Map();",
      "  for (let i = 0, len = items.length; i < len; i++) map.set(items[i][key], items[i]);",
      "  __indexCache.set(items, { key: key, map: map });",
      "  return map;",
      "}"
    );
  }
  if (helpers.length > 0) js.splice(1, 0, ...helpers);

  mkdirSync(options.outDir, { recursive: true });

  const body = js.join("\n");
  const exportList = exportNames.join(", ");
  const esm = `${body}\nexport { ${exportList} };\n`;
  const cjs = `${body}\nmodule.exports = { ${exportList} };\n`;
  const types = `${dts.join("\n")}\n`;

  const files = [
    writeFile(options.outDir, "index.mjs", esm),
    writeFile(options.outDir, "index.cjs", cjs),
    writeFile(options.outDir, "index.d.ts", types),
    writeFile(options.outDir, "index.d.cts", types),
    writeFile(
      options.outDir,
      "package.json",
      `${JSON.stringify(
        {
          name: packageName,
          version: "0.0.0",
          type: "module",
          main: "./index.cjs",
          module: "./index.mjs",
          types: "./index.d.ts",
          exports: {
            "./package.json": "./package.json",
            ".": {
              types: "./index.d.ts",
              import: "./index.mjs",
              require: "./index.cjs",
            },
          },
          sideEffects: false,
        },
        null,
        2
      )}\n`
    ),
  ];

  return { files, skipped };
}

function tryEmit<TValue>(
  schema: string,
  operation: string,
  skipped: SkippedOperation[],
  emit: () => TValue
): TValue | undefined {
  try {
    return emit();
  } catch (error) {
    skipped.push({
      schema,
      operation,
      reason: error instanceof Error ? error.message : String(error),
    });
    return undefined;
  }
}

/**
 * Serializes validator bindings into const declarations. Returns undefined
 * when any value is a function or otherwise not representable as source.
 */
function inlineBindings(names: readonly string[], values: readonly unknown[]): string[] | undefined {
  const lines: string[] = [];

  for (let index = 0; index < names.length; index++) {
    const value = values[index];
    const literal = serializeBindingValue(value);

    if (literal === undefined) return undefined;

    lines.push(`const ${names[index]} = ${literal};`);
  }

  return lines;
}

function inlineCodecBindings(names: readonly string[], values: readonly unknown[]): string[] | undefined {
  const lines: string[] = [];

  for (let index = 0; index < names.length; index++) {
    const name = names[index];
    const value = values[index];

    if (name === "__enc") {
      lines.push("const __enc = new TextEncoder();");
      continue;
    }

    if (name === "__dec") {
      lines.push("const __dec = new TextDecoder();");
      continue;
    }

    const literal = serializeBindingValue(value);

    if (literal === undefined) return undefined;

    lines.push(`const ${name} = ${literal};`);
  }

  return lines;
}

function serializeBindingValue(value: unknown): string | undefined {
  if (value instanceof RegExp) return String(value);
  if (value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return JSON.stringify(value);
  }
  if (value === undefined) return "undefined";
  if (Array.isArray(value)) {
    const parts = value.map(serializeBindingValue);

    if (parts.some((part) => part === undefined)) return undefined;
    return `[${parts.join(", ")}]`;
  }

  return undefined;
}

/**
 * Relative type-import path from the generated package to the dev's schema
 * file: POSIX separators, TS extensions mapped to their emitted JS forms
 * (nodenext resolves them back to the source at typecheck time).
 */
function typeImportSpecifier(outDir: string, sourceFile: string): string {
  const relativePath = relative(resolve(outDir), resolve(sourceFile)).split("\\").join("/");
  const mapped = relativePath
    .replace(/\.mts$/, ".mjs")
    .replace(/\.cts$/, ".cjs")
    .replace(/\.ts$/, ".js");

  return mapped.startsWith(".") ? mapped : `./${mapped}`;
}

const AOT_OPS = new Set([
  "is",
  "parse",
  "safeParse",
  "hash",
  "equal",
  "clone",
  "stringify",
  "mask",
  "sanitize",
  "codec",
]);

/** Reads the extras key list from a `JIT.compile(schema, ops, extras)` marker. */
function readExtraNames(input: SchemaInput): readonly string[] {
  const candidate = (input as { readonly extras?: unknown }).extras;

  if (Array.isArray(candidate) && candidate.every((key) => typeof key === "string")) {
    return candidate as readonly string[];
  }

  return [];
}

/** Reads the ops allowlist from a `JIT.compile(schema, ops)` marker input. */
function readRequestedOps(input: SchemaInput): readonly string[] | undefined {
  const candidate = (input as { readonly ops?: unknown }).ops;

  if (Array.isArray(candidate) && candidate.every((op) => typeof op === "string")) {
    return candidate as readonly string[];
  }

  return undefined;
}

function indentBlock(source: string): string[] {
  return source.split("\n").map((line) => (line.length > 0 ? `  ${line}` : line));
}

function writeFile(dir: string, name: string, content: string): string {
  const path = join(dir, name);

  writeFileSync(path, content);
  return path;
}
