packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true
  sharp: true
  "@tailwindcss/oxide": true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@fumadocs/tailwind@0.1.1'
  - fumadocs-core@16.11.3
  - fumadocs-ui@16.11.3

overrides:
  "@jit-compiler/cli-darwin-arm64": "link:./packages/jit-cli/native/darwin-arm64"
  "@jit-compiler/cli-darwin-x64": "link:./packages/jit-cli/native/darwin-x64"
  "@jit-compiler/cli-linux-arm64": "link:./packages/jit-cli/native/linux-arm64"
  "@jit-compiler/cli-linux-x64": "link:./packages/jit-cli/native/linux-x64"
  "@jit-compiler/cli-win32-x64": "link:./packages/jit-cli/native/win32-x64"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - "@tailwindcss/oxide"
  - unrs-resolver
