import { describe, expect, it } from "vitest";
import * as jit from "../packages/jit/src/index.js";

describe("public API manifest", () => {
  it("keeps the runtime namespace surface explicit", () => {
    expect({
      root: Object.keys(jit).sort(),
      jit: Object.keys(jit.JIT).sort(),
      class: Object.keys(jit.JIT.class).sort(),
      ddd: Object.keys(jit.JIT.ddd).sort(),
      compare: Object.keys(jit.JIT.compare).sort(),
    }).toMatchInlineSnapshot(`
      {
        "class": [
          "abstract",
          "clone",
          "diff",
          "equals",
          "factory",
          "getter",
          "hashCode",
          "isFailure",
          "json",
          "method",
          "mixin",
          "noConstructor",
          "override",
          "private",
          "protected",
          "public",
          "setter",
          "with",
        ],
        "compare": [
          "changed",
          "diff",
          "equal",
          "hash",
        ],
        "ddd": [
          "$extends",
          "abstract",
          "aggregateRoot",
          "domainEvent",
          "entity",
          "softDelete",
          "timestamps",
          "uniqueIdentifier",
          "valueObject",
          "versioned",
          "watchedList",
        ],
        "jit": [
          "KeyedWatchedList",
          "WatchedList",
          "access",
          "any",
          "api",
          "array",
          "bigint",
          "binary",
          "boolean",
          "brand",
          "cacheKey",
          "canonical",
          "class",
          "clone",
          "codec",
          "coerce",
          "compare",
          "cqrs",
          "csv",
          "custom",
          "date",
          "ddd",
          "default",
          "discriminatedUnion",
          "dto",
          "enum",
          "file",
          "format",
          "from",
          "function",
          "index",
          "instanceOf",
          "int",
          "intersection",
          "iso",
          "json",
          "jsonSchema",
          "lazy",
          "literal",
          "lookup",
          "map",
          "mapSchema",
          "match",
          "migrate",
          "mock",
          "nan",
          "ndjson",
          "never",
          "not",
          "null",
          "nullable",
          "nullish",
          "number",
          "object",
          "ops",
          "optional",
          "pipe",
          "process",
          "project",
          "promise",
          "readonly",
          "record",
          "refine",
          "regex",
          "regexes",
          "rules",
          "security",
          "set",
          "sort",
          "state",
          "stream",
          "string",
          "symbol",
          "templateLiteral",
          "templateLiterals",
          "temporal",
          "transform",
          "tuple",
          "undefined",
          "union",
          "unknown",
          "validate",
          "void",
          "xor",
        ],
        "root": [
          "AOT",
          "AST",
          "Builder",
          "Compiler",
          "Errors",
          "Host",
          "JIT",
          "PipelineAST",
          "Runtime",
          "Tooling",
          "Transform",
        ],
      }
    `);
  });

  it("rejects removed transition aliases at compile time", () => {
    if (Object.is(1, 2)) {
      // @ts-expect-error overwrite was removed from the final API
      jit.JIT.overwrite;
      // @ts-expect-error overwrite was never a class capability in the final API
      jit.JIT.class.overwrite;
    }
  });
});
