import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { runCompiledShowcase } from "../compiled/index.js";
import { runRuntimeShowcase } from "../runtime/index.js";

describe("runtime and AOT examples", () => {
  it("executes the full runtime showcase", async () => {
    const result = await runRuntimeShowcase();

    expect(result).toMatchObject({
      mode: "runtime",
      validUsers: 3,
      adminIds: [1],
      lazyIds: [1, 3],
      visitedUsers: 2,
      equalClone: true,
      cloneDetached: true,
      diffPaths: ["name"],
      stableHash: true,
      updatedName: "Ada Byron",
      publicKeys: ["id", "name", "role"],
      binaryAdminIds: [1, 3],
      binaryScore: 21.25,
      socketUserId: 1,
    });
    expect(result.invalidIssues).toBeGreaterThan(1);
    expect(result.codecBytes).toBeGreaterThan(0);
    expect(result.streamedUsers).toBe(3);
  });

  it("executes import-free generated AOT operations", async () => {
    const result = await runCompiledShowcase();
    const source = readFileSync(join(import.meta.dirname, "../compiled/generated/index.mjs"), "utf8");
    const manifest = JSON.parse(
      readFileSync(join(import.meta.dirname, "../compiled/generated/manifest.json"), "utf8")
    ) as {
      readonly artifacts: readonly { readonly name: string; readonly operations: readonly string[] }[];
      readonly modules: readonly { readonly source: string }[];
    };

    expect(result).toMatchObject({
      mode: "aot",
      validUsers: 3,
      adminIds: [1],
      lazyIds: [1, 3],
      visitedUsers: 2,
      equalClone: true,
      cloneDetached: true,
      diffPaths: ["name"],
      stableHash: true,
      socketUserId: 1,
    });
    expect(source).toContain("Generated by jit");
    expect(source).not.toContain('from "@jit/compiler"');
    expect(source).not.toContain("@jit/compiler/runtime");
    expect(manifest.modules[0]?.source).toBe("../catalog.jit.ts");
    expect(manifest.artifacts.find((artifact) => artifact.name === "User")?.operations).toEqual([
      "is",
      "parse",
      "safeParse",
      "equal",
      "clone",
      "diff",
      "hash",
      "stringify",
      "fromJSON",
      "mask",
      "sanitize",
      "codec",
    ]);
  });

  it("loads the generated CommonJS entrypoint without the compiler", () => {
    const output = execFileSync(
      process.execPath,
      [
        "-e",
        'const { User } = require("./compiled/generated/index.cjs"); process.stdout.write(String(User.is({ id: 1, name: "Ada", email: "ada@example.com", role: "admin", active: true, score: 10, tags: ["jit"], createdAt: "2026-07-01T10:00:00Z" })));',
      ],
      { cwd: join(import.meta.dirname, ".."), encoding: "utf8" }
    );

    expect(output).toBe("true");
  });
});
