import { readFileSync } from "node:fs";
import { join } from "node:path";
import { runCompiledShowcase } from "../compiled/index.js";
import { runRuntimeShowcase } from "../runtime/index.js";

describe("runtime and AOT examples", () => {
  it("executes the full runtime showcase", async () => {
    const result = await runRuntimeShowcase();

    expect(result).toMatchObject({
      mode: "runtime",
      validUsers: 3,
      adminIds: [1],
      lazyIds: [1, 3],
      visitedUsers: 2,
      equalClone: true,
      cloneDetached: true,
      diffPaths: ["name"],
      stableHash: true,
      updatedName: "Ada Byron",
      publicKeys: ["id", "name", "role"],
      binaryAdminIds: [1, 3],
      binaryScore: 21.25,
      socketUserId: 1,
    });
    expect(result.invalidIssues).toBeGreaterThan(1);
    expect(result.codecBytes).toBeGreaterThan(0);
    expect(result.streamedUsers).toBe(3);
  });

  it("executes import-free generated AOT operations", async () => {
    const result = await runCompiledShowcase();
    const source = readFileSync(join(import.meta.dirname, "../compiled/generated/index.ts"), "utf8");

    expect(result).toMatchObject({
      mode: "aot",
      validUsers: 3,
      adminIds: [1],
      lazyIds: [1, 3],
      visitedUsers: 2,
      equalClone: true,
      cloneDetached: true,
      diffPaths: ["name"],
      stableHash: true,
      socketUserId: 1,
    });
    expect(source).toContain("Generated by jit");
    expect(source).not.toContain('from "@jit-compiler/jit"');
    expect(source).not.toContain("@jit-compiler/jit/runtime");
    // Types are named after the schemas the declaration file declared.
    expect(source).toContain("export type User = {");
    expect(source).toContain("export type UserList = User[];");
    expect(source).toContain(
      "export { Users, UserJsonSchema, findActiveAdmins, iterateActiveUsers, toPublicUser, visitActiveUsers };"
    );
    // The JSON Schema document is inlined as data; the translator never ships.
    expect(source).toContain('"$schema":"https://json-schema.org/draft/2020-12/schema"');
  });

  it("loads the generated typed entrypoint without the compiler", async () => {
    const { Users } = (await import("../compiled/generated/index.js")) as {
      Users: { is: (value: unknown) => boolean };
    };

    expect(
      Users.is({
        id: 1,
        name: "Ada",
        email: "ada@example.com",
        role: "admin",
        active: true,
        score: 10,
        tags: ["jit"],
        createdAt: "2026-07-01T10:00:00Z",
      })
    ).toBe(true);
  });
});
