import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { withEntrypoint } from "../store";

/**
 * The workspace editor resolves its import against declaration files served as
 * Monaco extra libs, and a missing one shows up as
 * `Cannot find module '@jit-compiler/jit/define'` — an error that looks like a
 * broken editor rather than a missing file. These lock the two ends of that
 * chain: the package really exports both subpaths, and the manifest the editor
 * downloads really carries a declaration for each.
 */

const siteRoot = resolve(import.meta.dirname, "../../..");
const packageJsonPath = resolve(siteRoot, "../../packages/jit/package.json");
const manifestPath = resolve(siteRoot, "public/playground/jit-dts.json");

const SUBPATHS = ["runtime", "define"] as const;

describe("workspace entrypoints", () => {
  const manifest = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
    exports: Record<string, unknown>;
  };

  it.each(SUBPATHS)("the package exports ./%s, which the editor imports", (subpath) => {
    expect(manifest.exports).toHaveProperty(`./${subpath}`);
  });

  it("writes an import the package actually exports", () => {
    for (const mode of ["run", "generate"] as const) {
      const [importLine] = withEntrypoint("const User = JIT.object({});", mode).split("\n");
      const specifier = /"(@jit-compiler\/jit[^"]*)"/.exec(importLine)?.[1];

      expect(specifier).toBeDefined();
      const subpath = specifier?.replace("@jit-compiler/jit", ".") ?? "";
      expect(manifest.exports).toHaveProperty(subpath);
    }
  });

  /**
   * Generated by `pnpm gen:dts` during dev and build. When it has not been
   * generated in this checkout there is nothing to assert, but when it exists
   * every editable entrypoint must be in it.
   */
  it.runIf(existsSync(manifestPath))("ships a declaration file for every entrypoint", () => {
    const dts = JSON.parse(readFileSync(manifestPath, "utf8")) as { files: Record<string, string> };

    for (const subpath of SUBPATHS) {
      expect(Object.keys(dts.files)).toContain(`${subpath}.d.ts`);
      expect(dts.files[`${subpath}.d.ts`].length).toBeGreaterThan(0);
    }
  });
});
