import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { PersistedRun, PersistedSuite } from "./shared/persist.js";

// Regenerates docs/internal/BENCH.md from bench/results/*.latest.json.
// Ratio = JIT avg / best non-biased competitor avg; ratio > 1 means JIT loses.

const resultsDir = fileURLToPath(new URL("./results/", import.meta.url));
const outputPath = fileURLToPath(new URL("../docs/internal/BENCH.md", import.meta.url));

interface ScenarioReport {
  readonly suite: string;
  readonly scenario: string;
  readonly jitAvg: number;
  readonly bestName: string;
  readonly bestAvg: number;
  readonly ratio: number;
  readonly biasedOnly: boolean;
}

function formatNs(ns: number): string {
  if (ns < 1_000) return `${ns.toFixed(2)} ns`;
  if (ns < 1_000_000) return `${(ns / 1_000).toFixed(2)} µs`;
  return `${(ns / 1_000_000).toFixed(2)} ms`;
}

function splitName(name: string): { impl: string; scenario: string } {
  const separator = name.indexOf(" / ");
  if (separator === -1) return { impl: name, scenario: name };
  return { impl: name.slice(0, separator), scenario: name.slice(separator + 3) };
}

function buildReports(suite: PersistedSuite): ScenarioReport[] {
  const byScenario = new Map<string, PersistedRun[]>();

  for (const run of suite.runs) {
    if (!run.stats) continue;
    // Scenario names alone collide across ops (pick and omit both use
    // "medium object"), so group by the persisted scenario key.
    const scenario = suite.scenarios?.[run.name] ?? splitName(run.name).scenario;
    const bucket = byScenario.get(scenario);
    if (bucket) bucket.push(run);
    else byScenario.set(scenario, [run]);
  }

  const reports: ScenarioReport[] = [];

  for (const [scenario, runs] of byScenario) {
    const jitRun = runs.find((run) => splitName(run.name).impl.startsWith("JIT "));
    if (!jitRun?.stats) continue;

    const honest = runs.filter((run) => run !== jitRun && !(run.name in suite.biased));
    const biased = runs.filter((run) => run !== jitRun && run.name in suite.biased);
    // Fall back to biased competitors (flagged below) when no honest one exists.
    const pool = honest.length > 0 ? honest : biased;
    if (pool.length === 0) continue;

    let best = pool[0];
    for (const run of pool) {
      if ((run.stats?.avg ?? Number.POSITIVE_INFINITY) < (best.stats?.avg ?? Number.POSITIVE_INFINITY)) best = run;
    }
    if (!best.stats) continue;

    reports.push({
      suite: suite.suite,
      scenario,
      jitAvg: jitRun.stats.avg,
      bestName: splitName(best.name).impl,
      bestAvg: best.stats.avg,
      ratio: jitRun.stats.avg / best.stats.avg,
      biasedOnly: honest.length === 0,
    });
  }

  return reports;
}

function renderTable(reports: readonly ScenarioReport[]): string {
  const rows = reports.map((report) => {
    const flag = report.biasedOnly ? " ⚠ biased-only" : "";
    return `| ${report.suite} | ${report.scenario} | ${formatNs(report.jitAvg)} | ${report.bestName}${flag} | ${formatNs(report.bestAvg)} | ${report.ratio.toFixed(2)}× |`;
  });

  return [
    "| Suite | Scenario | JIT avg | Best competitor | Their avg | JIT/them |",
    "|---|---|---|---|---|---|",
    ...rows,
  ].join("\n");
}

if (!existsSync(resultsDir)) {
  console.error("[bench:report] no bench/results directory — run the bench suites first (pnpm bench:all)");
  process.exit(1);
}

const suiteFiles = readdirSync(resultsDir).filter((file) => file.endsWith(".latest.json"));

if (suiteFiles.length === 0) {
  console.error("[bench:report] no *.latest.json in bench/results — run the bench suites first (pnpm bench:all)");
  process.exit(1);
}

const suites = suiteFiles.map((file) => JSON.parse(readFileSync(join(resultsDir, file), "utf8")) as PersistedSuite);
const allReports = suites.flatMap(buildReports);

const losses = allReports.filter((report) => report.ratio > 1).sort((a, b) => b.ratio - a.ratio);
const wins = allReports.filter((report) => report.ratio <= 1).sort((a, b) => a.ratio - b.ratio);

const capturedAt = suites.map((suite) => `${suite.suite}: ${suite.capturedAt}`).join(", ");
const biasNotes = suites
  .flatMap((suite) => Object.entries(suite.biased).map(([name, reason]) => `- \`${name}\` — ${reason}`))
  .join("\n");

const markdown = `# BENCH — latest results

Generated by \`pnpm bench:report\`. Do not edit by hand.

Node ${suites[0]?.node ?? "?"} · ${suites[0]?.platform ?? "?"} (WSL2 — treat ratios, not absolutes)
Captured: ${capturedAt}

## Losses (JIT slower than best competitor, worst first)

${losses.length > 0 ? renderTable(losses) : "None — JIT wins every scenario."}

## Wins

${renderTable(wins)}

## Biased comparisons (excluded from honest ratios)

${biasNotes.length > 0 ? biasNotes : "None."}
`;

mkdirSync(fileURLToPath(new URL("../docs/internal/", import.meta.url)), { recursive: true });
writeFileSync(outputPath, markdown);
console.log(`[bench:report] wrote docs/internal/BENCH.md (${allReports.length} scenarios, ${losses.length} losses)`);
