//! Native JIT artifact CLI.
//!
//! It reconstructs a generated file tree and does nothing else. It writes no
//! configuration, keeps no journal and leaves no state behind: what it needs
//! it is given on the command line, or it asks for on the terminal.

#![forbid(unsafe_code)]

mod fs_ops;
mod registry;

use std::fmt;
use std::fs;
use std::io::{self, IsTerminal as _, Read as _, Write as _};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use clap::{Args, CommandFactory as _, Parser, Subcommand, ValueEnum};
use clap_complete::{Shell, generate};
use jit_artifact::{
    ArtifactFile, ArtifactReport, ArtifactTree, Compression, PackOptions, Profile,
    VerifiedArtifact, decode, pack_tree,
};
use rebyte_format::{RelativeArtifactPath, SecurityLimits};
use serde::Serialize;
use thiserror::Error;

use crate::registry::Environment;

const MAX_STDIN_BYTES: u64 = SecurityLimits::SIMPLE_ARTIFACT.max_token_bytes;

#[derive(Debug, Parser)]
#[command(
    name = "jit-artifact",
    version,
    about = "Verify and reconstruct generated JIT TypeScript exactly",
    long_about = "Creates deterministic offline jit1_ tokens and reconstructs signed jlr1_ Lab references. Artifacts never install dependencies, execute commands or run lifecycle hooks."
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Pack a generated file tree into a deterministic jit1_ token.
    Pack(PackCommand),
    /// Download, authenticate and reconstruct a signed jlr1_ Lab artifact.
    Add(AddCommand),
    /// Inspect bounded metadata after complete integrity verification.
    Inspect(ReadCommand),
    /// Verify structure, decompression and every content digest.
    Verify(ReadCommand),
    /// Compare verified artifact bytes with a local output directory.
    Diff(OutputCommand),
    /// Preview and reconstruct a verified artifact.
    Apply(ApplyCommand),
    /// Compute a BLAKE3 digest for a local file.
    Hash(HashCommand),
    /// Report protocol, environment and platform capabilities.
    Doctor(DoctorCommand),
    /// Generate shell completion definitions.
    Completions {
        /// Target shell.
        #[arg(value_enum)]
        shell: Shell,
    },
}

/// Which Lab a signed reference is allowed to have come from.
#[derive(Debug, Args)]
struct RegistryArguments {
    /// Exact registry origin to trust; overrides --env and the environment.
    #[arg(long, value_name = "URL")]
    registry: Option<String>,
    /// Named environment to trust.
    #[arg(long, value_enum)]
    env: Option<Environment>,
}

#[derive(Debug, Args)]
struct AddCommand {
    /// Signed jlr1_ reference generated by the JIT Lab.
    token: String,
    /// Project root that confines every file action.
    #[arg(long, default_value = ".")]
    root: PathBuf,
    /// Relative output directory; overrides the signed suggestion.
    #[arg(long)]
    output_root: Option<String>,
    /// Verify and preview without modifying the filesystem.
    #[arg(long)]
    dry_run: bool,
    /// Skip confirmation; never skips verification or path checks.
    #[arg(long)]
    yes: bool,
    /// What to do about a file that exists and differs.
    #[arg(long, value_enum)]
    conflict: Option<ConflictArgument>,
    #[command(flatten)]
    registry: RegistryArguments,
    /// Emit a stable JSON report.
    #[arg(long)]
    json: bool,
}

#[derive(Debug, Args)]
struct PackCommand {
    /// Generated file or directory to encode.
    input: PathBuf,
    /// Suggested relative reconstruction directory.
    #[arg(long)]
    output_root: Option<String>,
    /// Compression strategy.
    #[arg(long, value_enum, default_value = "auto")]
    compression: CompressionArgument,
    /// Compression effort.
    #[arg(long, value_enum, default_value = "balanced")]
    profile: ProfileArgument,
    /// Disable adaptive dictionary training.
    #[arg(long)]
    no_dictionary: bool,
    /// Write the token to a new file instead of stdout.
    #[arg(short, long)]
    output: Option<PathBuf>,
    /// Emit a stable JSON report.
    #[arg(long)]
    json: bool,
}

#[derive(Debug, Args)]
struct ReadCommand {
    #[command(flatten)]
    input: TokenInput,
    /// Emit a stable JSON report.
    #[arg(long)]
    json: bool,
}

#[derive(Debug, Args)]
struct OutputCommand {
    #[command(flatten)]
    input: TokenInput,
    /// Project root that confines every file action.
    #[arg(long, default_value = ".")]
    root: PathBuf,
    /// Relative output directory; overrides the token's own suggestion.
    #[arg(long)]
    output_root: Option<String>,
    /// Include unified text patches.
    #[arg(long)]
    patch: bool,
    /// Emit a stable JSON report.
    #[arg(long)]
    json: bool,
}

#[derive(Debug, Args)]
struct ApplyCommand {
    #[command(flatten)]
    output: OutputCommand,
    /// Verify and preview without modifying the filesystem.
    #[arg(long)]
    dry_run: bool,
    /// Skip confirmation; never skips verification or path checks.
    #[arg(long)]
    yes: bool,
    /// What to do about a file that exists and differs.
    #[arg(long, value_enum)]
    conflict: Option<ConflictArgument>,
}

#[derive(Debug, Args)]
struct HashCommand {
    /// Regular file to hash.
    file: PathBuf,
    /// Check the digest instead of only printing it.
    #[arg(long)]
    expected: Option<String>,
    /// Emit a stable JSON report.
    #[arg(long)]
    json: bool,
}

#[derive(Debug, Args)]
struct DoctorCommand {
    /// Project root.
    #[arg(long, default_value = ".")]
    root: PathBuf,
    #[command(flatten)]
    registry: RegistryArguments,
    /// Emit a stable JSON report.
    #[arg(long)]
    json: bool,
}

#[derive(Debug, Args)]
struct TokenInput {
    /// Inline jit1_ token, or - to read standard input.
    #[arg(value_name = "TOKEN", conflicts_with = "file")]
    token: Option<String>,
    /// Read a token from a file.
    #[arg(long, value_name = "PATH")]
    file: Option<PathBuf>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub(crate) enum ConflictArgument {
    /// Stop rather than change a file that exists and differs.
    Abort,
    /// Replace it.
    Overwrite,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
enum CompressionArgument {
    Auto,
    Zstd,
    None,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
enum ProfileArgument {
    Fast,
    Balanced,
    Maximum,
}

#[derive(Debug, Error)]
#[error("{message}")]
pub(crate) struct CliError {
    code: u8,
    message: String,
}

impl CliError {
    fn new(code: u8, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }

    pub(crate) fn usage(message: impl Into<String>) -> Self {
        Self::new(2, message)
    }

    pub(crate) fn config(message: impl Into<String>) -> Self {
        Self::new(3, message)
    }

    pub(crate) fn integrity(message: impl Into<String>) -> Self {
        Self::new(4, message)
    }

    pub(crate) fn unsafe_path(message: impl Into<String>) -> Self {
        Self::new(5, message)
    }

    pub(crate) fn conflict(message: impl Into<String>) -> Self {
        Self::new(6, message)
    }

    pub(crate) fn io(message: impl Into<String>) -> Self {
        Self::new(7, message)
    }
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("jit-artifact error: {error}");
            ExitCode::from(error.code)
        }
    }
}

fn run() -> Result<(), CliError> {
    let cli = Cli::parse();

    match cli.command {
        Command::Pack(command) => run_pack(&command),
        Command::Add(command) => run_add(&command),
        Command::Inspect(command) => run_inspect(&command),
        Command::Verify(command) => run_verify(&command),
        Command::Diff(command) => run_diff(&command),
        Command::Apply(command) => run_apply(&command),
        Command::Hash(command) => run_hash(&command),
        Command::Doctor(command) => run_doctor(&command),
        Command::Completions { shell } => {
            generate(
                shell,
                &mut Cli::command(),
                "jit-artifact",
                &mut io::stdout(),
            );
            Ok(())
        }
    }
}

fn run_add(command: &AddCommand) -> Result<(), CliError> {
    let registry = registry::resolve(command.registry.registry.as_deref(), command.registry.env)?;
    let downloaded = registry::fetch(&command.token, &registry)?;
    let options = PackOptions {
        suggested_path: Some(downloaded.output_root.clone()),
        compression: Compression::None,
        profile: Profile::Fast,
        dictionary: false,
    };
    let (token, _) = pack_tree(&ArtifactTree::from_files(downloaded.files), &options)
        .map_err(|error| CliError::integrity(error.to_string()))?;
    let artifact = decode(&token).map_err(|error| CliError::integrity(error.to_string()))?;
    let output = fs_ops::resolve_output(
        &command.root,
        command
            .output_root
            .as_deref()
            .or(Some(&downloaded.output_root)),
        &artifact,
    )?;
    let report = fs_ops::diff(&artifact, &output)?;

    if command.json {
        print_json(&report)?;
    } else {
        println!(
            "authenticated {} from {} ({})",
            downloaded.hash, registry.origin, registry.source
        );
        print_diff(&report);
        println!("No dependencies will be installed. No commands will be executed.");
    }
    if command.dry_run {
        return Ok(());
    }
    if !command.json && !command.yes && !confirm("Write these verified files?")? {
        return Err(CliError::conflict("cancelled"));
    }

    let conflict = decide_conflict(
        command.conflict,
        report.updates,
        command.yes || command.json,
    )?;
    let applied = fs_ops::apply(&artifact, &output, &command.root, conflict)?;
    if command.json {
        print_json(&applied)
    } else {
        print_applied(&applied);
        Ok(())
    }
}

fn run_pack(command: &PackCommand) -> Result<(), CliError> {
    let tree = read_artifact_tree(&command.input)?;
    let options = PackOptions {
        suggested_path: command.output_root.clone(),
        compression: compression(command.compression),
        profile: profile(command.profile),
        dictionary: !command.no_dictionary,
    };
    let (token, report) =
        pack_tree(&tree, &options).map_err(|error| CliError::integrity(error.to_string()))?;

    if let Some(output) = &command.output {
        write_new(output, format!("{token}\n").as_bytes())?;
    }
    if command.json {
        print_json(&PackReport {
            report,
            token: command.output.is_none().then_some(token),
            output: command
                .output
                .as_ref()
                .map(|path| path.to_string_lossy().into_owned()),
        })
    } else if command.output.is_none() {
        println!("{token}");
        Ok(())
    } else {
        println!(
            "wrote {}",
            command
                .output
                .as_ref()
                .map_or_else(String::new, |path| path.display().to_string())
        );
        Ok(())
    }
}

fn run_inspect(command: &ReadCommand) -> Result<(), CliError> {
    let artifact = read_verified(&command.input)?;
    if command.json {
        print_json(&artifact.report())
    } else {
        print_report(&artifact.report(), "integrity verified");
        Ok(())
    }
}

fn run_verify(command: &ReadCommand) -> Result<(), CliError> {
    let artifact = read_verified(&command.input)?;
    if command.json {
        print_json(&VerifyReport {
            valid: true,
            report: artifact.report(),
        })
    } else {
        print_report(
            &artifact.report(),
            "valid, byte-exact, publisher unauthenticated",
        );
        Ok(())
    }
}

fn run_diff(command: &OutputCommand) -> Result<(), CliError> {
    let artifact = read_verified(&command.input)?;
    let output = fs_ops::resolve_output(&command.root, command.output_root.as_deref(), &artifact)?;
    let mut report = fs_ops::diff(&artifact, &output)?;
    if !command.patch {
        for file in &mut report.files {
            file.patch = None;
        }
    }
    if command.json {
        print_json(&report)
    } else {
        print_diff(&report);
        Ok(())
    }
}

fn run_apply(command: &ApplyCommand) -> Result<(), CliError> {
    let artifact = read_verified(&command.output.input)?;
    let output = fs_ops::resolve_output(
        &command.output.root,
        command.output.output_root.as_deref(),
        &artifact,
    )?;
    let mut report = fs_ops::diff(&artifact, &output)?;
    if !command.output.patch {
        for file in &mut report.files {
            file.patch = None;
        }
    }

    if command.output.json {
        print_json(&report)?;
    } else {
        print_report(
            &artifact.report(),
            "integrity verified; publisher unauthenticated",
        );
        print_diff(&report);
        println!("No dependencies will be installed. No commands will be executed.");
    }
    if command.dry_run {
        return Ok(());
    }
    if !command.output.json && !command.yes && !confirm("Write these verified files?")? {
        return Err(CliError::conflict("cancelled"));
    }

    let conflict = decide_conflict(
        command.conflict,
        report.updates,
        command.yes || command.output.json,
    )?;
    let applied = fs_ops::apply(&artifact, &output, &command.output.root, conflict)?;
    if command.output.json {
        print_json(&applied)
    } else {
        print_applied(&applied);
        Ok(())
    }
}

fn run_hash(command: &HashCommand) -> Result<(), CliError> {
    let metadata = fs::symlink_metadata(&command.file).map_err(|error| {
        CliError::io(format!(
            "cannot inspect {}: {error}",
            command.file.display()
        ))
    })?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(CliError::unsafe_path("hash input must be a regular file"));
    }
    let bytes = fs::read(&command.file).map_err(|error| {
        CliError::io(format!("cannot read {}: {error}", command.file.display()))
    })?;
    let digest = blake3::hash(&bytes).to_hex().to_string();
    let matches = command
        .expected
        .as_ref()
        .is_none_or(|expected| expected.eq_ignore_ascii_case(&digest));
    if !matches {
        return Err(CliError::integrity(format!("digest mismatch: {digest}")));
    }
    if command.json {
        print_json(&HashReport {
            file: command.file.to_string_lossy().into_owned(),
            digest,
            matches,
        })
    } else {
        println!("{digest}  {}", command.file.display());
        Ok(())
    }
}

fn run_doctor(command: &DoctorCommand) -> Result<(), CliError> {
    let registry = registry::resolve(command.registry.registry.as_deref(), command.registry.env)?;
    let report = DoctorReport {
        schema_version: 1,
        protocols: ["jit1", "jlr1"],
        authenticated_references: true,
        trusted_registry: registry.origin.clone(),
        registry_source: registry.source,
        root: command.root.to_string_lossy().into_owned(),
        max_token_bytes: SecurityLimits::SIMPLE_ARTIFACT.max_token_bytes,
        max_output_bytes: SecurityLimits::SIMPLE_ARTIFACT.max_uncompressed_payload_bytes,
        max_files: SecurityLimits::SIMPLE_ARTIFACT.max_file_count,
    };
    if command.json {
        print_json(&report)
    } else {
        println!("jit-artifact doctor");
        println!("protocols: {}", report.protocols.join(", "));
        println!(
            "trusted registry: {} (from {})",
            report.trusted_registry, report.registry_source
        );
        println!("select another with --env local, --env production or --registry <url>");
        println!("authentication: jlr1_ signed; jit1_ integrity-only");
        println!("state written: none besides the reconstructed files");
        println!(
            "limits: token={} output={} files={}",
            report.max_token_bytes, report.max_output_bytes, report.max_files
        );
        Ok(())
    }
}

/**
What to do about files that already exist, decided here rather than assumed.

Overwriting without being told to is how a generator eats work someone did by
hand, and refusing outright is how it becomes useless the second time it is
run. So the answer is asked for when there is someone to ask, and demanded as a
flag when there is not.
*/
fn decide_conflict(
    explicit: Option<ConflictArgument>,
    updates: usize,
    unattended: bool,
) -> Result<ConflictArgument, CliError> {
    if let Some(conflict) = explicit {
        return Ok(conflict);
    }
    if updates == 0 {
        return Ok(ConflictArgument::Abort);
    }
    if unattended || !io::stdin().is_terminal() {
        return Err(CliError::conflict(format!(
            "{updates} file(s) already exist and differ; pass --conflict overwrite to replace them"
        )));
    }
    if confirm(&format!("Replace {updates} file(s) that already exist?"))? {
        Ok(ConflictArgument::Overwrite)
    } else {
        Err(CliError::conflict("cancelled"))
    }
}

fn read_verified(input: &TokenInput) -> Result<VerifiedArtifact, CliError> {
    let token = read_token(input)?;
    decode(&token).map_err(|error| CliError::integrity(error.to_string()))
}

fn read_token(input: &TokenInput) -> Result<String, CliError> {
    let bytes = if let Some(path) = &input.file {
        read_bounded_file(path, MAX_STDIN_BYTES)?
    } else {
        let token = input
            .token
            .as_deref()
            .ok_or_else(|| CliError::usage("TOKEN or --file is required"))?;
        if token == "-" {
            read_bounded(io::stdin().lock(), MAX_STDIN_BYTES)?
        } else {
            token.as_bytes().to_vec()
        }
    };
    String::from_utf8(bytes)
        .map(|token| token.trim().to_owned())
        .map_err(|_| CliError::usage("token is not UTF-8"))
}

/// Reads a generated tree, keeping the directories it declares.
fn read_artifact_tree(input: &Path) -> Result<ArtifactTree, CliError> {
    let metadata = fs::symlink_metadata(input)
        .map_err(|error| CliError::io(format!("cannot inspect {}: {error}", input.display())))?;
    if metadata.file_type().is_symlink() {
        return Err(CliError::unsafe_path(
            "artifact input cannot be a symbolic link",
        ));
    }
    if metadata.is_file() {
        let name = input
            .file_name()
            .and_then(|value| value.to_str())
            .ok_or_else(|| CliError::unsafe_path("input filename is not portable UTF-8"))?;
        return Ok(ArtifactTree::from_files(vec![ArtifactFile::new(
            name,
            read_bounded_file(input, SecurityLimits::SIMPLE_ARTIFACT.max_single_file_bytes)?,
        )]));
    }
    if !metadata.is_dir() {
        return Err(CliError::usage(
            "artifact input must be a regular file or directory",
        ));
    }
    let mut tree = ArtifactTree::default();
    collect_tree(input, input, &mut tree)?;
    Ok(tree)
}

fn collect_tree(root: &Path, directory: &Path, tree: &mut ArtifactTree) -> Result<(), CliError> {
    let mut entries = fs::read_dir(directory)
        .map_err(|error| CliError::io(format!("cannot read {}: {error}", directory.display())))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| CliError::io(format!("cannot read directory entry: {error}")))?;
    entries.sort_by_key(fs::DirEntry::file_name);

    for entry in entries {
        let path = entry.path();
        let metadata = fs::symlink_metadata(&path)
            .map_err(|error| CliError::io(format!("cannot inspect {}: {error}", path.display())))?;
        if metadata.file_type().is_symlink() {
            return Err(CliError::unsafe_path(format!(
                "symbolic link is forbidden: {}",
                path.display()
            )));
        }
        let relative = relative_path(root, &path)?;

        if metadata.is_dir() {
            let before = tree.files.len();
            collect_tree(root, &path, tree)?;
            // A directory with files under it is implied by their paths. One
            // with none is only expressible as an entry of its own, and it is
            // part of the layout that was declared.
            if tree.files.len() == before {
                tree.directories.push(relative);
            }
            continue;
        }
        if !metadata.is_file() {
            return Err(CliError::unsafe_path(format!(
                "unsupported input: {}",
                path.display()
            )));
        }
        let bytes =
            read_bounded_file(&path, SecurityLimits::SIMPLE_ARTIFACT.max_single_file_bytes)?;
        tree.files
            .push(ArtifactFile::new(relative, bytes).executable(is_executable(&metadata)));
    }
    Ok(())
}

fn relative_path(root: &Path, path: &Path) -> Result<String, CliError> {
    let relative = path
        .strip_prefix(root)
        .map_err(|_| CliError::unsafe_path("input escaped source root"))?
        .to_str()
        .ok_or_else(|| CliError::unsafe_path("input path is not UTF-8"))?
        .replace(std::path::MAIN_SEPARATOR, "/");
    RelativeArtifactPath::new(&relative)
        .map_err(|error| CliError::unsafe_path(format!("invalid input path: {error}")))?;

    Ok(relative)
}

fn read_bounded_file(path: &Path, maximum: u64) -> Result<Vec<u8>, CliError> {
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| CliError::io(format!("cannot inspect {}: {error}", path.display())))?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(CliError::unsafe_path(format!(
            "not a regular file: {}",
            path.display()
        )));
    }
    if metadata.len() > maximum {
        return Err(CliError::usage(format!(
            "{} has {} bytes; maximum is {maximum}",
            path.display(),
            metadata.len()
        )));
    }
    let file = fs::File::open(path)
        .map_err(|error| CliError::io(format!("cannot open {}: {error}", path.display())))?;
    read_bounded(file, maximum)
}

fn read_bounded(mut reader: impl io::Read, maximum: u64) -> Result<Vec<u8>, CliError> {
    let mut bytes = Vec::new();
    reader
        .by_ref()
        .take(maximum.saturating_add(1))
        .read_to_end(&mut bytes)
        .map_err(|error| CliError::io(format!("cannot read input: {error}")))?;
    let length =
        u64::try_from(bytes.len()).map_err(|_| CliError::usage("input length overflow"))?;
    if length > maximum {
        return Err(CliError::usage(format!(
            "input has {length} bytes; maximum is {maximum}"
        )));
    }
    Ok(bytes)
}

fn write_new(path: &Path, bytes: &[u8]) -> Result<(), CliError> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)
        .map_err(|error| CliError::io(format!("cannot create {}: {error}", parent.display())))?;
    let mut file = fs::File::options()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|error| {
            CliError::conflict(format!("cannot create {}: {error}", path.display()))
        })?;
    file.write_all(bytes)
        .and_then(|()| file.sync_all())
        .map_err(|error| CliError::io(format!("cannot write {}: {error}", path.display())))
}

const fn compression(value: CompressionArgument) -> Compression {
    match value {
        CompressionArgument::Auto => Compression::Auto,
        CompressionArgument::Zstd => Compression::Zstd,
        CompressionArgument::None => Compression::None,
    }
}

const fn profile(value: ProfileArgument) -> Profile {
    match value {
        ProfileArgument::Fast => Profile::Fast,
        ProfileArgument::Balanced => Profile::Balanced,
        ProfileArgument::Maximum => Profile::Maximum,
    }
}

fn confirm(question: &str) -> Result<bool, CliError> {
    if !io::stdin().is_terminal() {
        return Err(CliError::conflict(
            "confirmation requires a terminal; pass --yes in automation",
        ));
    }
    eprint!("{question} (y/N) ");
    io::stderr()
        .flush()
        .map_err(|error| CliError::io(format!("cannot prompt: {error}")))?;
    let mut answer = String::new();
    io::stdin()
        .read_line(&mut answer)
        .map_err(|error| CliError::io(format!("cannot read confirmation: {error}")))?;
    Ok(matches!(answer.trim(), "y" | "Y" | "yes" | "YES"))
}

fn print_report(report: &ArtifactReport, status: &str) {
    println!("JIT Artifact");
    println!("  status: {status}");
    println!("  digest: {}", report.envelope_digest);
    println!(
        "  files: {}  bytes: {} -> {}  compression: {}",
        report.files.len(),
        report.original_bytes,
        report.stored_bytes,
        report.compression
    );
    for directory in &report.directories {
        println!("  - {directory}/");
    }
    for file in &report.files {
        println!("  - {} ({} bytes)", file.path, file.bytes);
    }
}

fn print_diff(report: &fs_ops::DiffReport) {
    println!(
        "changes: {} create, {} update, {} unchanged, {} new directory(ies)",
        report.creates,
        report.updates,
        report.unchanged,
        report.directories.len()
    );
    for directory in &report.directories {
        println!("  {:9} {directory}/", "MKDIR");
    }
    for file in &report.files {
        println!("  {:9} {}", file.change.to_uppercase(), file.path);
        if let Some(patch) = &file.patch {
            print!("{patch}");
        }
    }
}

fn print_applied(report: &fs_ops::ApplyReport) {
    println!(
        "wrote {} file(s), {} directory(ies), {} byte(s) to {}",
        report.files_written, report.directories_created, report.bytes_written, report.output
    );
}

fn print_json(value: &impl Serialize) -> Result<(), CliError> {
    serde_json::to_writer_pretty(io::stdout().lock(), value)
        .map_err(|error| CliError::io(format!("cannot encode JSON: {error}")))?;
    println!();
    Ok(())
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct PackReport {
    report: ArtifactReport,
    token: Option<String>,
    output: Option<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct VerifyReport {
    valid: bool,
    report: ArtifactReport,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct HashReport {
    file: String,
    digest: String,
    matches: bool,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct DoctorReport {
    schema_version: u16,
    protocols: [&'static str; 2],
    authenticated_references: bool,
    trusted_registry: String,
    registry_source: &'static str,
    root: String,
    max_token_bytes: u64,
    max_output_bytes: u64,
    max_files: u32,
}

#[cfg(unix)]
fn is_executable(metadata: &fs::Metadata) -> bool {
    use std::os::unix::fs::PermissionsExt as _;

    metadata.permissions().mode() & 0o111 != 0
}

#[cfg(not(unix))]
fn is_executable(_metadata: &fs::Metadata) -> bool {
    false
}

impl fmt::Display for ConflictArgument {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Abort => formatter.write_str("abort"),
            Self::Overwrite => formatter.write_str("overwrite"),
        }
    }
}
